Repository godaddy-wordpress/coblocks, pull requests merged in 2019-06, with the labels that each got.

#586 Tweak asset directory for WordPress.org assets
  .dev/bin/deploy-plugin.sh
  .wordpress-org/banner-1544x500.jpg
  .wordpress-org/banner-772x250.jpg
  .wordpress-org/icon-128x128.jpg
  .wordpress-org/icon-256x256.jpg
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.gif
  .wordpress-org/screenshot-3.gif
  .wordpress-org/screenshot-4.gif
  .wordpress-org/screenshot-5.gif
  .wordpress-org/screenshot-6.gif
  gruntfile.js
Labels: Cleanup

#587 Organize GitHub files and add issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .gitignore
Labels: Cleanup

#591 Tweak language of our issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: Cleanup

#583 Change the Row block layout panelBody label from "Layout" to "Style"
  src/blocks/row/components/inspector.js
Labels: UX

#582 Update gallery block icons
  src/blocks/gallery-carousel/icons.js
  src/blocks/gallery-masonry/icons.js
  src/blocks/gallery-stacked/icons.js
Labels: UX

#596 Remove references to the deprecated CoBlocks Block Manager
  .wordpress-org/screenshot-6.gif
  README.md
  includes/admin/class-coblocks-getting-started-page.php
  readme.txt
Labels: Cleanup

#600 Update Facebook logo to new brand guidelines
  dist/images/social/facebook.svg
Labels: [Block] Social

#598 Fix Row Block selected state
  src/blocks/row/column/components/edit.js
  src/blocks/row/components/edit.js
  src/blocks/row/styles/editor.scss
Labels: UI

#584 Add new category for gallery blocks
  src/blocks/gallery-carousel/index.js
  src/blocks/gallery-masonry/index.js
  src/blocks/gallery-stacked/index.js
  src/utils/block-category.js
Labels: Do Not Merge, UX

#580 Add optional links to individual gallery images
  languages/coblocks-js.pot
  src/blocks/gallery-masonry/edit.js
  src/blocks/gallery-masonry/index.js
  src/blocks/gallery-masonry/inspector.js
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-stacked/edit.js
  src/blocks/gallery-stacked/index.js
  src/blocks/gallery-stacked/inspector.js
  src/blocks/gallery-stacked/styles/editor.scss
  src/components/block-gallery/gallery-image.js
  src/components/block-gallery/gallery-link-settings.js
  src/components/block-gallery/options/link-options.js
  src/components/block-gallery/shared/attributes.js
  src/components/block-gallery/shared/transforms.js
  src/components/block-gallery/styles/editor.scss
  src/components/block-gallery/styles/editor/_gallery-item-link.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/utils/helper.js
Labels: UX

#578 Rename the "Social block" to "Share block"
  src/blocks.js
  src/blocks/share/components/colors.js
  src/blocks/share/components/controls.js
  src/blocks/share/components/edit.js
  src/blocks/share/components/inspector.js
  src/blocks/share/index.js
  src/blocks/share/index.php
  src/blocks/share/styles/editor.scss
  src/blocks/share/styles/style.scss
Labels: UX

#604 Introduce filter to nest Getting Started page in a parent menu item
  includes/admin/class-coblocks-getting-started-page.php
Labels: Enhancement

#605 Double clicking the rendered map brings up the location editor
  src/blocks/map/components/edit.js
Labels: Enhancement, [Block] Map

#609 Fix duplicate Google map script enqueued in editor
  includes/class-coblocks-google-map-block.php
  src/js/coblocks-google-maps.js
Labels: [Block] Map

#611 Fix map block erroring on initial add without an address
  src/blocks/map/components/edit.js
Labels: [Block] Map

#590 Add Menu block
  languages/coblocks-js.pot
  src/blocks.js
  src/blocks/food-and-drinks/appender.js
  src/blocks/food-and-drinks/block.json
  src/blocks/food-and-drinks/edit.js
  src/blocks/food-and-drinks/food-item/block.json
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/icons.js
  src/blocks/food-and-drinks/food-item/index.js
  src/blocks/food-and-drinks/food-item/inspector.js
  src/blocks/food-and-drinks/food-item/save.js
  src/blocks/food-and-drinks/food-item/styles/editor.scss
  src/blocks/food-and-drinks/food-item/styles/style.scss
  src/blocks/food-and-drinks/icons.js
  src/blocks/food-and-drinks/index.js
  src/blocks/food-and-drinks/inspector.js
  src/blocks/food-and-drinks/save.js
  src/blocks/food-and-drinks/styles/editor.scss
  src/blocks/food-and-drinks/styles/style.scss
  src/styles/style.scss
  src/styles/style/_tooltips.scss
  src/utils/block-helpers.js
Labels: Enhancement, New Block

#622 Tweak the bug report issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: Cleanup
