Repository godaddy-wordpress/coblocks, pull requests merged in 2019-05, with the labels that each got.

#517 Fix row row handles
  src/blocks/row/column/components/edit.js
  src/blocks/row/styles/editor.scss
Labels: [Block] Row

#518 [tiny] Fixes #499
  src/styles/style/_background-parallax.scss
Labels: Enhancement, accessibility

#526 Fix Row Block UI for WordPress 5.2/Gutenberg 5.6
  src/blocks/media-card/styles/editor.scss
  src/blocks/row/styles/editor.scss
Labels: Bug, [Block] Row

#527 Tweak file headers
  class-coblocks.php
  includes/admin/class-coblocks-action-links.php
  includes/admin/class-coblocks-admin-footer.php
  includes/admin/class-coblocks-feedback.php
  includes/admin/class-coblocks-getting-started-page.php
  includes/admin/class-coblocks-install.php
  includes/admin/class-coblocks-url-generator.php
  includes/class-coblocks-accordion-ie-support.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-body-classes.php
  includes/class-coblocks-font-loader.php
  includes/class-coblocks-generated-styles.php
  includes/class-coblocks-google-map.php
  includes/class-coblocks-post-meta.php
  includes/class-coblocks-register-blocks.php
  includes/class-coblocks-settings.php
  includes/get-dynamic-blocks.php
  src/blocks/social/index.php
Labels: Cleanup

#528 Update package
  gulpfile.js
  package-lock.json
  package.json
Labels: Cleanup

#529 Fix class file names (PHPCS)
  class-coblocks.php
  includes/class-coblocks-block-settings.php
  includes/class-coblocks-google-map-block.php
Labels: Cleanup

#530 Replace @@pkg.title with "CoBlocks"
  includes/admin/class-coblocks-action-links.php
  includes/admin/class-coblocks-feedback.php
  includes/class-coblocks-body-classes.php
Labels: Cleanup

#531 Update gulp with new gallery block scripts
  gulpfile.js
Labels: Enhancement

#536 Remove extraneous plugin action links
  includes/admin/class-coblocks-action-links.php
Labels: Cleanup

#519 Introduce a form block
  class-coblocks.php
  dist/images/list/checkbox-rounded.svg
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-form.php
  package-lock.json
  package.json
  src/blocks.js
  src/blocks/form/components/fields/field-label.js
  src/blocks/form/components/fields/field-name.js
  src/blocks/form/components/fields/field-textarea.js
  src/blocks/form/components/fields/field.js
  src/blocks/form/components/notice.js
  src/blocks/form/components/submit-button.js
  src/blocks/form/edit.js
  src/blocks/form/icons.js
  src/blocks/form/index.js
  src/blocks/form/styles/editor.scss
  src/blocks/form/styles/notice.scss
  src/blocks/form/styles/style.scss
  src/blocks/icon/components/icons.js
  src/blocks/icon/components/svgs.js
  src/blocks/row/components/icons.js
  src/blocks/shape-divider/components/dividers.js
  src/blocks/shape-divider/components/icons.js
  src/components/background/icons.js
  src/components/media-filter-control/icons.js
  src/utils/brand-assets.js
  src/utils/icons.js
Labels: New Block

#545 Update map block placeholder string
  languages/coblocks.pot
  package-lock.json
  src/blocks/map/components/edit.js
  src/blocks/map/components/inspector.js
Labels: [Block] Map

#480 Deprecate the CoBlocks Block Manager in place of core
  src/blocks.js
  src/sidebars/block-manager/components/modal.js
  src/sidebars/block-manager/deprecated.js
  src/sidebars/block-manager/index.js
Labels: Enhancement

#546 Tweak/sass color variables
  src/blocks/accordion/accordion-item/styles/style.scss
  src/blocks/accordion/styles/editor.scss
  src/blocks/buttons/styles/editor.scss
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/dynamic-separator/styles/style.scss
  src/blocks/gallery-stacked/styles/style.scss
  src/blocks/gif/styles/editor.scss
  src/blocks/gist/styles/style.scss
  src/blocks/hero/styles/editor.scss
  src/blocks/icon/styles/editor.scss
  src/blocks/map/styles/editor.scss
  src/blocks/media-card/styles/editor.scss
  src/blocks/media-card/styles/style.scss
  src/blocks/row/styles/editor.scss
  src/blocks/shape-divider/styles/editor.scss
  src/blocks/social/styles/editor.scss
  src/blocks/social/styles/style.scss
  src/common.scss
  src/components/background/styles/editor.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/components/block-gallery/styles/editor/_remove-gallery-item-button.scss
  src/components/block-gallery/styles/style.scss
  src/components/block-gallery/styles/style/_core-themes.scss
  src/components/block-gallery/styles/style/_flickity.scss
  src/components/dimensions-control/styles/editor.scss
  src/components/grid-control/styles/editor.scss
  src/components/orientation/styles/editor.scss
  src/components/responsive-base-control/styles/editor.scss
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/size-control/styles/editor.scss
  src/components/typography-controls/styles/editor.scss
  src/components/visual-dropdown/styles/editor.scss
  src/sidebars/block-manager/styles/editor.scss
  src/styles/admin.scss
  src/styles/admin/_dashboard-widget.scss
  src/styles/admin/_modal-frame.scss
  src/styles/admin/_notices.scss
  src/styles/admin/_template-count.scss
  src/styles/admin/_tooltips.scss
  src/styles/editor.scss
  src/styles/editor/_is-transient.scss
  src/styles/getting-started.scss
Labels: Cleanup

#554 Remove the block mover from the Media Card row block
  src/blocks/media-card/styles/editor.scss
Labels: UX, [Block] Media Card

#556 Introduce a honeypot spam check field
  includes/class-coblocks-form.php
  src/blocks/form/edit.js
  src/blocks/form/styles/editor.scss
  src/blocks/form/styles/style.scss
  src/js/coblocks-google-recaptcha.js
Labels: [Block] Form

#547 Add @wordpress/postcss-themes support
  .babelrc
  .dev/config/externals.js
  .dev/config/paths.js
  .dev/config/post-css-config.js
  .dev/config/webpack.config.dev.js
  .dev/config/webpack.config.prod.js
  .dev/scripts/build.js
  .dev/scripts/start.js
  .dev/scripts/translate.js
  .gitignore
  languages/coblocks-js.pot
  languages/coblocks.pot
  package-lock.json
  package.json
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/form/edit.js
  src/blocks/gist/components/gist.js
  src/blocks/hero/styles/editor.scss
  src/blocks/map/components/inspector.js
  src/blocks/media-card/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/blocks/shape-divider/styles/editor.scss
  src/common.scss
  src/components/block-gallery/styles/editor/_flickity-arrows.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/components/block-gallery/styles/editor/_remove-gallery-item-button.scss
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/size-control/styles/editor.scss
  src/components/typography-controls/styles/editor.scss
  src/components/visual-dropdown/styles/editor.scss
  src/styles/editor.scss
  wp-org-assets/screenshot-2.gif
  wp-org-assets/screenshot-3.gif
  wp-org-assets/screenshot-4.gif
  wp-org-assets/screenshot-5.gif
  wp-org-assets/screenshot-6.gif
Labels: Enhancement

#568 Remove unused editor styling from the Media Card block
  src/blocks/media-card/styles/editor.scss
Labels: Do Not Merge

#564 Add error notice to Map block
  languages/coblocks-js.pot
  languages/coblocks.pot
  src/blocks/map/components/edit.js
  wp-org-assets/screenshot-2.gif
  wp-org-assets/screenshot-3.gif
  wp-org-assets/screenshot-4.gif
  wp-org-assets/screenshot-5.gif
  wp-org-assets/screenshot-6.gif
Labels: UX, [Block] Map

#563 Add image reordering to gallery blocks
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-masonry/edit.js
  src/blocks/gallery-stacked/edit.js
  src/components/block-gallery/gallery-image.js
  src/components/block-gallery/styles/editor.scss
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
  src/components/block-gallery/styles/editor/_radius.scss
  src/components/block-gallery/styles/editor/_remove-gallery-item-button.scss
Labels: Enhancement, UX

#572 Move the Marker Size RangeControl below Height
  src/blocks/map/components/inspector.js
Labels: UX

#573 Fix issue with Gutenberg 5.8 and the Media Card block resizable box
  src/blocks/media-card/styles/editor.scss
Labels: [Block] Media Card

#566 Add/social circular style
  src/blocks/social/components/edit.js
  src/blocks/social/components/inspector.js
  src/blocks/social/index.js
  src/blocks/social/index.php
  src/blocks/social/styles/editor.scss
  src/blocks/social/styles/style.scss
Labels: Enhancement, [Block] Social
