Repository godaddy-wordpress/coblocks, pull requests merged in 2019-11, with the labels that each got.

#1089 Clean up Gist block toolbar
  src/blocks/gist/controls.js
Labels: [Block] Gist, cleanup

#1087 Enhance DimensionsControls with vw and vh units
  src/components/dimensions-control/index.js
  src/components/dimensions-control/styles/editor.scss
Labels: [Type] Enhancement

#1076 Add keepPlaceholderOnFocus prop to Author block text placeholders
  src/blocks/author/edit.js
Labels: UX, [Block] Author

#1091 Enable certain core blocks in the form block
  src/blocks/form/edit.js
Labels: [Block] Form

#1085 Use BlockIcon component for Placeholder Icons
  src/blocks/gif/edit.js
  src/blocks/gist/edit.js
  src/blocks/gist/gist.js
  src/blocks/gist/styles/editor.scss
  src/blocks/row/edit.js
Labels: [Block] Gif, [Block] Gist, [Block] Row, cleanup

#1071 Add block preview for Collage Gallery block
  src/blocks/gallery-collage/index.js
Labels: [Block] Collage Gallery, [Type] Enhancement

#1095 Adjust Accordion block default background color for improved theme compatibility
  src/blocks/accordion/accordion-item/styles/editor.scss
  src/blocks/accordion/accordion-item/styles/style.scss
Labels: [Block] Accordion, [Type] Bug

#1055 Allow theme colors in Row block placeholder
  src/components/visual-dropdown/styles/editor.scss
Labels: [Block] Row, wp 5.3

#1056 ISBAT have consistent component styling in WordPress 5.3
  src/blocks/hero/styles/editor.scss
  src/components/dimensions-control/index.js
  src/components/dimensions-control/styles/editor.scss
  src/components/grid-control/styles/editor.scss
  src/components/responsive-base-control/index.js
  src/components/responsive-base-control/styles/editor.scss
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/size-control/styles/editor.scss
Labels: [Type] Code Quality, wp 5.3

#1096 Tweak VisualDropdown component for 5.3+
  src/components/visual-dropdown/styles/editor.scss
Labels: wp 5.3

#1077 Remove block preview example for Shape Divider block
  src/blocks/shape-divider/index.js
Labels: [Block] Shape Divider, [Type] Bug

#1101 Remove field block.json files shift metadata into index.js
  src/blocks/form/block.json
  src/blocks/form/fields/checkbox/block.json
  src/blocks/form/fields/checkbox/index.js
  src/blocks/form/fields/date/block.json
  src/blocks/form/fields/date/index.js
  src/blocks/form/fields/email/block.json
  src/blocks/form/fields/email/index.js
  src/blocks/form/fields/hidden/block.json
  src/blocks/form/fields/hidden/index.js
  src/blocks/form/fields/name/block.json
  src/blocks/form/fields/name/index.js
  src/blocks/form/fields/phone/block.json
  src/blocks/form/fields/phone/index.js
  src/blocks/form/fields/radio/block.json
  src/blocks/form/fields/radio/index.js
  src/blocks/form/fields/select/block.json
  src/blocks/form/fields/select/index.js
  src/blocks/form/fields/textarea/block.json
  src/blocks/form/fields/textarea/index.js
  src/blocks/form/fields/website/block.json
  src/blocks/form/fields/website/index.js
  src/blocks/form/index.js
Labels: [Block] Form

#1084 Improve the column control of the Posts and Post Carousel blocks
  src/blocks/post-carousel/inspector.js
  src/blocks/posts/inspector.js
Labels: [Block] Post Carousel, [Block] Posts, [Type] Bug

#1066 Fix code display styles of the Gist block with the TwentyTwenty theme
  src/blocks/gist/styles/style.scss
Labels: [Block] Gist, [Theme] 2020, [Type] Bug

#1065 Bump WordPress Core support to 5.3
  package.json
Labels: waiting, wp 5.3

#1038 Use the jQuery global to avoid script conflicts with Gif block
  src/blocks/gif/edit.js
Labels: [Block] Gif, [Type] Bug, [Type] Code Quality, wp 5.3

#1097 Remove CoBlocks getting started guide
  .dev/tests/phpunit/includes/admin/test-coblocks-getting-started-page.php
  .dev/tests/phpunit/test-class-coblocks.php
  class-coblocks.php
  dist/css/coblocks-getting-started.css
  dist/css/coblocks-getting-started.min.css
  dist/images/admin/icon-notice.jpg
  dist/images/admin/video-2.jpg
  dist/images/admin/video-3.jpg
  dist/images/admin/video.jpg
  gruntfile.js
  includes/admin/class-coblocks-getting-started-page.php
  src/js/vendors/lity.js
  src/styles/getting-started.scss
Labels: [Type] Enhancement

#1107 Add !important properties for the advanced top/bottom margin
  src/extensions/advanced-controls/styles/style.scss
Labels: [Type] Bug

#1108 Remove custom Color Settings for the heading block
  src/extensions/colors/index.js
  src/extensions/colors/inspector.js
Labels: [Type] Bug, wp 5.3

#1109 Tweak Dynamic HR styling for TwentyTwenty
  src/blocks/dynamic-separator/deprecated.js
  src/blocks/dynamic-separator/edit.js
  src/blocks/dynamic-separator/index.js
  src/blocks/dynamic-separator/save.js
  src/blocks/dynamic-separator/styles/style.scss
Labels: [Theme] 2020

#1100 Add block movers to Pricing Table Items
  src/blocks/pricing-table/controls.js
  src/blocks/pricing-table/edit.js
  src/blocks/pricing-table/pricing-table-item/styles/editor.scss
  src/blocks/pricing-table/styles/editor.scss
Labels: [Block] Pricing Table, [Type] Enhancement

#1112 Fix label position on Gutter and Thumbnail size controls.
  src/blocks/gallery-collage/inspector.js
  src/blocks/posts/inspector.js
Labels: UI, [Block] Collage Gallery, [Block] Posts, [Type] Bug

#1113 PHPCS: Use full array syntax
  composer.lock
  includes/admin/class-coblocks-action-links.php
  includes/admin/class-coblocks-crop-settings.php
  includes/admin/class-coblocks-install.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-form.php
  includes/class-coblocks-post-meta.php
  src/blocks/post-carousel/index.php
  src/blocks/posts/index.php
Labels: [Type] Code Quality

#1115 Use string name in server side rendered block registration
  src/blocks/post-carousel/index.php
  src/blocks/posts/index.php
  src/blocks/share/index.php
  src/blocks/social-profiles/index.php
Labels: [Type] Bug

#1114 Fix grunt build issues
  gruntfile.js
  package.json
Labels: [Type] Bug

#1106 Use external Wikipedia CC licensed images in block examples
  src/blocks/author/index.js
  src/blocks/gallery-carousel/index.js
  src/blocks/gallery-collage/index.js
  src/blocks/gallery-masonry/index.js
  src/blocks/gallery-stacked/index.js
  src/blocks/logos/index.js
  src/blocks/media-card/index.js
Labels: [Block] Author, [Block] Carousel Gallery, [Block] Collage Gallery, [Block] Logos & Badges, [Block] Masonry Gallery, [Block] Media Card, [Block] Stacked Gallery, [Type] Enhancement

#1121 Add Server Rendered block.json files to the build
  gruntfile.js
Labels: [Type] Bug, [Type] Build Tooling

#1119 Replace ... with horizontal ellipsis (…)
  .dev/tests/phpunit/includes/test-coblocks-accordion-ie-support.php
  src/blocks/accordion/accordion-item/edit.js
  src/blocks/alert/edit.js
  src/blocks/click-to-tweet/edit.js
  src/blocks/features/feature/edit.js
  src/blocks/food-and-drinks/edit.js
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/gallery-collage/edit.js
  src/blocks/gist/edit.js
  src/blocks/highlight/edit.js
  src/blocks/media-card/edit.js
  src/blocks/services/service/edit.js
Labels: cleanup

#1124 Remove unused example images
  dist/images/examples/author.jpg
  dist/images/examples/gallery-1.jpg
  dist/images/examples/gallery-2.jpg
  dist/images/examples/gallery-3.jpg
  dist/images/examples/gallery-4.jpg
  dist/images/examples/gallery-5.jpg
  dist/images/examples/gallery-6.jpg
  dist/images/examples/gallery-7.jpg
  dist/images/examples/logo-1.jpg
  dist/images/examples/logo-2.jpg
Labels: cleanup

#1125 Replace Media Card block MediaPlaceholder icon with image/video icon
  src/blocks/media-card/icons.js
  src/blocks/media-card/media-container.js
Labels: UX, [Block] Media Card

#1127 Posts columns div selector correction. Posts grid not displaying as columns.
  src/blocks/posts/index.php
Labels: [Block] Posts, [Type] Bug

#1131 Fix Posts block render loop when switching to horizontal style
  src/blocks/posts/inspector.js
Labels: [Block] Posts, [Type] Bug

#1133 Remove 1.17.1 changelog updates
  readme.txt
Labels: cleanup

#1135 ensure all __() functions use a text domain
  src/blocks/gallery-carousel/inspector.js
  src/blocks/map/edit.js
  src/components/background/panel.js
  src/extensions/advanced-controls/index.js
Labels: [Type] Bug, cleanup

#1147 Ignore SVN externals in CircleCI
  .dev/bin/install-wp-tests.sh
Labels: CircleCI

#1118 Remove excess admin styles from /src/
  src/styles/admin.scss
  src/styles/admin/_dashboard-columns.scss
  src/styles/admin/_dashboard-widget.scss
  src/styles/admin/_mixins.scss
  src/styles/admin/_modal-frame.scss
  src/styles/admin/_modal.scss
  src/styles/admin/_notices.scss
  src/styles/admin/_template-count.scss
Labels: cleanup

#1141 Add lightbox support to Collage block
  includes/class-coblocks-block-assets.php
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/inspector.js
  src/blocks/gallery-collage/save.js
  src/blocks/gallery-masonry/styles/style.scss
  src/components/block-gallery/styles/style/_lightbox.scss
Labels: [Block] Collage Gallery, [Type] Enhancement

#1138 Update classes used in editor styling for consistency
  src/blocks/accordion/styles/editor.scss
  src/blocks/author/styles/editor.scss
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/dynamic-separator/styles/editor.scss
  src/blocks/features/styles/editor.scss
  src/blocks/form/styles/editor.scss
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-stacked/styles/editor.scss
  src/blocks/gif/styles/editor.scss
  src/blocks/highlight/styles/editor.scss
  src/blocks/map/styles/editor.scss
  src/blocks/media-card/styles/editor.scss
  src/blocks/pricing-table/pricing-table-item/styles/editor.scss
  src/blocks/pricing-table/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/blocks/shape-divider/styles/editor.scss
  src/extensions/advanced-controls/styles/editor.scss
  src/extensions/button-controls/styles/editor.scss
  src/styles/editor/_dropzone.scss
Labels: cleanup

#1137 Add important flag to avatar image
  src/blocks/author/styles/style.scss
Labels: [Block] Author, [Type] Bug

#1110 Remove CoBlocks Block Manager
  .dev/tests/phpunit/includes/test-coblocks-block-settings.php
  .dev/tests/phpunit/test-class-coblocks.php
  class-coblocks.php
  includes/class-coblocks-block-settings.php
  src/blocks.js
  src/sidebars/block-manager/components/map-innerblocks.js
  src/sidebars/block-manager/components/modal.js
  src/sidebars/block-manager/components/options/disable-blocks.js
  src/sidebars/block-manager/deprecated.js
  src/sidebars/block-manager/index.js
  src/sidebars/block-manager/styles/editor.scss
Labels: cleanup, wp 5.3 + only

#1148 Remove unused constant
  .dev/tests/phpunit/test-class-coblocks.php
  class-coblocks.php
Labels: cleanup

#1123 Add top/bottom waves to core Cover block
  src/blocks.js
  src/extensions/cover-styles/index.js
  src/extensions/cover-styles/styles/style.scss
Labels: [Type] Enhancement

#1146 Allow for multiple field types with same label
  .dev/tests/phpunit/includes/test-coblocks-form.php
  includes/class-coblocks-form.php
Labels: [Block] Form, [Type] Bug

#1150 Allow Alert block to receive custom classes without breaking styles
  src/blocks/highlight/edit.js
Labels: [Block] Alert, [Type] Bug

#1074 Hide avatar placeholder on Author block when not in use
  src/blocks/author/edit.js
Labels: UX, [Block] Author

#1142 Update Gallery blocks to use core UX patterns
  src/blocks/gallery-carousel/controls.js
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-carousel/styles/style.scss
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/gallery-masonry/controls.js
  src/blocks/gallery-masonry/edit.js
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-stacked/controls.js
  src/blocks/gallery-stacked/edit.js
  src/blocks/gallery-stacked/styles/editor.scss
  src/components/block-gallery/gallery-placeholder.js
  src/components/block-gallery/gallery-uploader.js
  src/components/block-gallery/styles/editor.scss
  src/components/block-gallery/styles/editor/_radius.scss
  src/components/block-gallery/styles/editor/_uploader.scss
Labels: UX, [Block] Carousel Gallery, [Block] Collage Gallery, [Block] Masonry Gallery, [Block] Stacked Gallery, [Type] Enhancement

#1152 Explicitly set block classnames instead of using the generated className prop
  src/blocks/accordion/accordion-item/edit.js
  src/blocks/author/edit.js
  src/blocks/author/save.js
  src/blocks/click-to-tweet/controls.js
  src/blocks/click-to-tweet/edit.js
  src/blocks/gif/edit.js
Labels: [Type] Bug

#1128 Add Form block templates
  src/blocks/form/edit.js
  src/blocks/form/icons.js
  src/blocks/form/index.js
  src/blocks/form/layouts.js
  src/blocks/form/styles/editor.scss
Labels: [Block] Form, [Type] Enhancement

#1159 Update repo links
  .github/CONTRIBUTING.md
  README.md
  changelog.txt
  composer.json
  package.json
  readme.txt
  src/blocks/alert/edit.js
Labels: cleanup
