Repository godaddy-wordpress/coblocks, pull requests merged in 2020-12, with the labels that each got.

#1769 Improve Circle Ci configuration file readability
  .circleci/config.yml
Labels: [Type] Code Quality, [Type] Tests

#1770 Use a static php container in E2E pipeline
  .circleci/config.yml
Labels: [Type] Tests

#1765 WPEX-923 Unifying CSS linting across projects
  .stylelintrc.json
  package.json
  src/blocks/gallery-offset/styles/style.scss
  src/blocks/icon/styles/editor.scss
  src/blocks/media-card/styles/editor.scss
  src/blocks/posts/styles/style.scss
  src/blocks/pricing-table/styles/editor.scss
  src/blocks/pricing-table/styles/style.scss
  src/blocks/services/styles/legacy.scss
  src/blocks/share/styles/style.scss
  src/components/block-gallery/styles/editor/_core-themes.scss
  src/components/block-gallery/styles/style/_carousel.scss
  src/components/block-gallery/styles/style/_grid.scss
  src/components/block-gallery/styles/style/_margin-bottom.scss
  src/components/block-gallery/styles/style/_margin-left-negative.scss
  src/components/block-gallery/styles/style/_margin-left.scss
  src/components/block-gallery/styles/style/_margin-right-negative.scss
  src/components/block-gallery/styles/style/_margin-right.scss
  src/components/block-gallery/styles/style/_margin-top.scss
  src/components/block-gallery/styles/style/_padding.scss
  src/components/block-gallery/styles/style/gutter.scss
  src/extensions/media-text-styles/styles/style.scss
  src/styles/editor/columns.scss
  src/styles/mixins.scss
  src/styles/style/columns.scss
  yarn.lock
Labels: [Priority] Low, [Type] Code Quality

#1771 Use a symlink instead of copy
  .circleci/config.yml
Labels: [Type] Code Quality, [Type] Tooling

#1781 Bump tested up to version to 5.6
  class-coblocks.php
  package.json
  readme.txt
Labels: [Status] Needs Review

#1779 Add aria-labels to the CoBlocks Lightbox utility
  includes/class-coblocks-block-assets.php
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Code Quality
