Repository godaddy-wordpress/coblocks, pull requests merged in 2020-11, with the labels that each got.

#1747 Fix broken style previews
  src/blocks/share/styles/editor.scss
Labels: [Priority] High

#1738 Enhance Layout Selector to allow Image Category selector
  src/extensions/layout-selector/editor.scss
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/layout-selector-slot.js
Labels: [Status] Do Not Merge, [Status] In Progress

#1577 Layout selector performance improvements
  includes/class-coblocks-block-assets.php
  src/extensions/layout-selector/editor.scss
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/layout-selector-results.js
  src/extensions/layout-selector/test/layout-preview.spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1752 Add icons for animations UI
  src/extensions/animation/animation-types.js
  src/extensions/animation/controls.js
  src/extensions/animation/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1754 Define Layout Selector visibility in store
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/store.js
Labels: [Status] Needs Review

#1757 Add logic to deprecate typography controls from Click-To-Tweet block
  src/blocks/click-to-tweet/deprecated.js
  src/extensions/typography/index.js
Labels: [Status] Needs Review

#1763 Cypress E2E Testing Updates
  package.json
  src/blocks/hero/test/hero.cypress.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/padding-controls/test/padding-controls.cypress.js
  yarn.lock
Labels: [Type] Bug, [Type] Tests

#1764 Fix failing tests for Author and Alert blocks
  src/blocks/alert/test/alert.cypress.js
  src/blocks/author/test/author.cypress.js
Labels: [Type] Tests
