Repository godaddy-wordpress/coblocks, pull requests merged in 2020-08, with the labels that each got.

#1612 Update Development Readme section
  README.md
Labels: [Type] Docs

#1587 Fix Lightbox use with Go theme and Carousel Gallery block
  src/js/coblocks-lightbox.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1610 Prevent empty Advanced panel from showing on blocks
  .dev/bin/setup-test-specs.sh
  src/extensions/advanced-controls/index.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1609 Deprecate IconButton in favor of Button component
  src/blocks/accordion/edit.js
  src/blocks/author/controls.js
  src/blocks/author/styles/editor.scss
  src/blocks/events/appender.js
  src/blocks/events/styles/editor.scss
  src/blocks/food-and-drinks/appender.js
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/styles/editor.scss
  src/blocks/food-and-drinks/styles/editor.scss
  src/blocks/form/fields/coblocks-option.js
  src/blocks/form/fields/multi-field.js
  src/blocks/gallery-collage/edit.js
  src/blocks/gif/controls.js
  src/blocks/logos/controls.js
  src/blocks/media-card/media-container.js
  src/blocks/row/edit.js
  src/blocks/services/service/edit.js
  src/components/background/controls.js
  src/components/block-gallery/gallery-image.js
  src/components/crop-settings/index.js
  src/components/grid-control/toolbar.js
  src/components/typography-controls/index.js
  src/components/typography-controls/styles/editor.scss
Labels: [Status] Needs Review, [Type] Code Quality

#1608 Update CSS selectors to improve agnosticism across versions
  src/blocks/accordion/styles/editor.scss
  src/blocks/alert/test/alert.cypress.js
  src/blocks/author/styles/editor.scss
  src/blocks/buttons/styles/editor.scss
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/dynamic-separator/styles/editor.scss
  src/blocks/events/event-item/test/event-item.cypress.js
  src/blocks/events/styles/editor.scss
  src/blocks/events/test/events.cypress.js
  src/blocks/features/styles/editor.scss
  src/blocks/food-and-drinks/food-item/test/food-item.cypress.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/form/styles/editor.scss
  src/blocks/form/test/form.cypress.js
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/styles/editor.scss
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/styles/editor.scss
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/blocks/gif/styles/editor.scss
  src/blocks/hero/styles/editor.scss
  src/blocks/highlight/styles/editor.scss
  src/blocks/icon/styles/editor.scss
  src/blocks/logos/test/logos.cypress.js
  src/blocks/map/styles/editor.scss
  src/blocks/media-card/styles/editor.scss
  src/blocks/media-card/test/media-card.cypress.js
  src/blocks/post-carousel/styles/editor.scss
  src/blocks/posts/styles/editor.scss
  src/blocks/pricing-table/pricing-table-item/styles/editor.scss
  src/blocks/pricing-table/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/blocks/row/styles/style.scss
  src/blocks/services/service/styles/editor.scss
  src/blocks/shape-divider/styles/editor.scss
  src/components/block-gallery/styles/editor/_core-themes.scss
  src/extensions/button-controls/styles/editor.scss
  src/extensions/image-crop/styles/editor.scss
  src/extensions/layout-selector/editor.scss
  src/styles/mixins.scss
Labels: [Priority] High, [Status] Needs Review

#1614 Update tested to value to 5.5
  class-coblocks.php
  package.json
  readme.txt
Labels: [Type] Docs

#1582 Fix Accordion block ability to use nested blocks
  src/blocks/accordion/accordion-item/edit.js
Labels: [Status] Needs Review, [Type] Bug

#1586 Allow empty lines within the Price Table features list
  src/blocks/pricing-table/pricing-table-item/edit.js
  src/blocks/pricing-table/pricing-table-item/save.js
  src/blocks/pricing-table/styles/style.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1615 Fix test selectors used for the CoBlocks Settings E2E tests
  src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
Labels: [Type] Bug, [Type] Tests

#1622 Fix Icon block invalid block content within the editor
  .dev/tests/cypress/helpers.js
  src/blocks/icon/deprecated.js
  src/blocks/icon/deprecated/svgsfocusable.js
Labels: [Priority] Critical, [Status] Needs Review, [Type] Bug

#1621 Hide form reCAPTCHA panel on initial load
  src/blocks/form/edit.js
  src/blocks/form/test/form.cypress.js
Labels: [Priority] Low, [Type] Enhancement

#1616 Style block appenders better for WordPress 5.5
  src/blocks/accordion/edit.js
  src/blocks/accordion/styles/editor.scss
  src/blocks/accordion/test/accordion.cypress.js
  src/blocks/events/appender.js
  src/blocks/events/styles/editor.scss
  src/blocks/events/test/events.cypress.js
  src/blocks/food-and-drinks/appender.js
  src/blocks/food-and-drinks/styles/editor.scss
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/extensions/button-controls/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1633 Introduce Shape Divider deprecations related to extensions
  src/blocks/shape-divider/deprecated.js
  src/blocks/shape-divider/test/shape-divider.cypress.js
Labels: [Type] Bug

#1637 Fix SVG icon deprecation in the Food and Drinks block
  src/blocks/food-and-drinks/food-item/deprecated/deprecatedIcons.js
Labels: [Status] Needs Review, [Type] Bug

#1635 Fix list styling of Food and Drinks block when column classes exist
  src/blocks/food-and-drinks/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug

#1648 Fix alignment of descriptions in the editor settings modal
  src/extensions/coblocks-settings/styles/style.scss
Labels: [Status] Needs Review, [Type] Design

#1649 Fix Icon block style previews
  src/blocks/icon/styles/editor.scss
Labels: [Status] Needs Review, [Type] Bug

#1651 Migrate CoBlocks to use @wordpress/base-styles package
  package.json
  src/blocks/dynamic-separator/styles/editor.scss
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/components/block-gallery/styles/editor/_gallery-item-link.scss
  src/components/crop-settings/styles/editor.scss
  src/components/typography-controls/styles/editor.scss
  src/styles/editor/core/_breakpoints.scss
  src/styles/editor/core/_colors.scss
  src/styles/editor/core/_mixins.scss
  src/styles/editor/core/_variables.scss
  yarn.lock
Labels: [Type] Code Quality
