Repository godaddy-wordpress/coblocks, pull requests merged in 2020-05, with the labels that each got.

#1477 Remove a condition where a variable may not be defined
  includes/class-coblocks-block-assets.php
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#1479 Render a submit button if not found in the block content
  includes/class-coblocks-form.php
Labels: [Priority] Critical, [Status] Needs Review, [Type] Bug

#1487 Add Layout Selector controls to the CoBlocks Settings panel
  .dev/tests/cypress/helpers.js
  docs/hooks/settings-panel.md
  includes/class-coblocks-settings.php
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-store.js
  src/extensions/coblocks-settings/coblocks-settings.cypress.js
  src/layout-selector/index.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1492 [Fix] Add custom classes for Map block within the editor.
  src/blocks/map/edit.js
  src/blocks/map/test/map.cypress.js
Labels: [Priority] Low, [Status] Needs Review

#1509 Tweak display of + button in layout selector
  src/layout-selector/index.js
  src/layout-selector/style.scss
Labels: [Priority] Low, [Status] Needs Review, [Status] Ready to Merge

#1510 Add Undo/Redo capabilities to Layout Selector
  package-lock.json
  src/layout-selector/index.js
Labels: [Status] Needs Review, [Type] Bug

#1511 Improve conditional loading of scripts and styles
  .dev/tests/phpunit/includes/test-coblocks-block-assets.php
  .dev/tests/phpunit/test-class-coblocks.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-body-classes.php
Labels: [Priority] Critical, [Status] Needs Review, [Type] Bug

#1502 Update typography hooks docs.
  docs/hooks/settings-panel.md
  docs/hooks/typography-controls.md
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Docs

#1494 Apply styles for formats
  src/styles/style.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1498 Add some names to contributros.md
  CONTRIBUTORS.md
Labels: [Type] Docs
