Repository godaddy-wordpress/coblocks, pull requests merged in 2020-10, with the labels that each got.

#1700 Fix post carousel arrows/text-align when in an RTL environment
  src/blocks/post-carousel/styles/editor.scss
  src/blocks/post-carousel/styles/style.scss
Labels: [Type] Bug

#1701 Fix formattingControls console warnings
  src/blocks/click-to-tweet/edit.js
  src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/test/food-item.cypress.js
  src/blocks/form/fields/submit-button/edit.js
  src/blocks/pricing-table/pricing-table-item/edit.js
  src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js
Labels: [Type] Bug

#1699 Fix carousel arrows in an RTL environment
  src/blocks/gallery-carousel/styles/style.scss
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
Labels: [Status] Needs Review, [Type] Bug

#1703 Remove deprecated isLarge prop from button componnets
  src/blocks/events/edit.js
  src/blocks/form/edit.js
  src/blocks/icon/inspector.js
  src/blocks/map/edit.js
  src/blocks/map/inspector.js
  src/blocks/post-carousel/edit.js
  src/blocks/posts/edit.js
  src/blocks/row/edit.js
  src/components/crop-settings/index.js
  src/components/size-control/index.js
  src/extensions/layout-selector/index.js
Labels: [Priority] High, [Status] Needs Review, [Type] Code Quality

#1708 PR to allow Gallery Collage tests to pass
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
Labels: [Status] Needs Review, [Type] Bug, [Type] Tests

#1709 Allow Stacked Gallery tests to pass
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
Labels: [Status] Needs Review, [Type] Bug, [Type] Tests

#1667 ✨ Introduce animation control
  .dev/config/webpack.config.js
  includes/class-coblocks-block-assets.php
  package.json
  src/blocks.js
  src/extensions/animation/animation-types.js
  src/extensions/animation/controls.js
  src/extensions/animation/index.js
  src/extensions/animation/styles/editor.scss
  src/extensions/animation/styles/style.scss
  src/js/coblocks-animation.js
  src/js/coblocks-color-fix.js
  src/utils/helper.js
  src/utils/helper.spec.js
  yarn.lock
Labels: [Priority] High, [Status] Ready to Merge, [Type] Enhancement

#1716 Introduce image filters to core image block
  .dev/tests/cypress/helpers.js
  src/blocks.js
  src/components/media-filter-control/index.js
  src/components/media-filter-control/test/media-filter-control.cypress.js
  src/extensions/image-filter/index.js
Labels: [Status] In Progress, [Type] Enhancement, [Type] Needs Tests

#1721 Introduce an image filter preview to the media-filter-control component
  src/components/media-filter-control/index.js
Labels: [Type] Enhancement, [Type] Needs Tests

#1723 Fix image preview regressions
  src/components/media-filter-control/index.js
  src/components/media-filter-control/styles/editor.scss
  src/extensions/animation/styles/editor.scss
  src/extensions/animation/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug

#1724 Remove search keywords from Media Card block
  src/blocks/media-card/index.js
Labels: [Status] Needs Review

#1710 Fix image alignment within Lightbox when long captions exist
  src/components/block-gallery/styles/style/_lightbox.scss
Labels: Hacktoberfest, [Status] Needs Review, [Type] Bug

#1726 Improve UX of blocks with animations applied and playing
  src/extensions/animation/controls.js
  src/extensions/animation/index.js
Labels: [Status] Needs Review, [Type] Bug

#1718 Fix duplicated and remove deprecated gallery transforms
  src/blocks/gallery-carousel/test/transforms.spec.js
  src/blocks/gallery-carousel/transforms.js
  src/blocks/gallery-collage/test/transforms.spec.js
  src/blocks/gallery-collage/transforms.js
  src/blocks/gallery-masonry/test/transforms.spec.js
  src/blocks/gallery-masonry/transforms.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-offset/test/transforms.spec.js
  src/blocks/gallery-offset/transforms.js
  src/blocks/gallery-stacked/test/transforms.spec.js
  src/blocks/gallery-stacked/transforms.js
  src/components/block-gallery/shared/transforms.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#1730 Fix Gallery placeholder UX across blocks
  src/components/block-gallery/styles/editor.scss
Labels: [Status] Needs Review

#1711 Fix Row block and Typography Controls
  src/extensions/typography/index.js
Labels: [Priority] Critical, [Status] Needs Review, [Type] Bug

#1727 Initialize layout selector store with coblocksLayoutSelector localized var
  .dev/tests/cypress/helpers.js
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/store.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1732 Fix Features block column count controls
  src/blocks/features/edit.js
  src/blocks/features/inspector.js
  src/blocks/features/test/features.cypress.js
Labels: [Priority] Critical, [Type] Bug

#1736 Preserve gallery animations on transform
  src/components/block-gallery/shared/transforms.js
Labels: [Status] Needs Review, [Type] Enhancement

#1735 Filter the blocks passed into layout block preview
  .dev/tests/jest/setup-globals.js
  package.json
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/test/layout-preview.spec.js
  yarn.lock
Labels: [Status] In Progress, [Type] Enhancement

#1739 Define which version of composer to use within CI jobs
  .circleci/config.yml
Labels: [Priority] High, [Status] Needs Review
