Repository godaddy-wordpress/coblocks, pull requests merged in 2020-06, with the labels that each got.

#1507 Fix gallery block image selector UI
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
Labels: [Priority] Low, [Status] Needs Review

#1328 Optimize CircleCI Workflow
  .circleci/config.yml
  .dev/bin/install-dependencies.sh
  .dev/bin/setup-test-specs.sh
  .eslintrc.js
  composer.lock
  package-lock.json
  package.json
  yarn.lock
Labels: [Priority] High, [Status] Needs Review, [Type] Code Quality, [Type] Tests, [Type] Tooling

#1518 Fix advanced block spacing with Gutenberg plugin
  .prettierrc.js
  src/extensions/advanced-controls/index.js
  src/extensions/advanced-controls/styles/editor.scss
Labels: [Type] Bug, [Type] Gutenberg

#1505 Add appropriate margin between Services block placeholder and title
  src/blocks/services/service/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1522 Remove .prettierrc.js file from repository
  .prettierrc.js
Labels: [Type] Bug, [Type] Code Quality

#1521 Fix advanced spacing in the Layout Selector and Editor
  src/extensions/advanced-controls/index.js
Labels: [Type] Bug, [Type] Gutenberg

#1476 CSS Custom Properties for $spacing
  src/blocks/click-to-tweet/styles/style.scss
  src/blocks/events/event-item/styles/style.scss
  src/blocks/features/styles/legacy.scss
  src/blocks/features/styles/style.scss
  src/blocks/gallery-collage/styles/style.scss
  src/blocks/gallery-offset/styles/style.scss
  src/blocks/icon/test/__snapshots__/save.spec.js.snap
  src/blocks/post-carousel/styles/slick.scss
  src/blocks/post-carousel/styles/style.scss
  src/blocks/posts/styles/style.scss
  src/blocks/pricing-table/styles/editor.scss
  src/blocks/pricing-table/styles/style.scss
  src/blocks/row/styles/editor.scss
  src/blocks/row/styles/style.scss
  src/blocks/services/service/styles/style.scss
  src/blocks/services/styles/legacy.scss
  src/blocks/shape-divider/test/__snapshots__/save.spec.js.snap
  src/common.scss
  src/styles/editor/columns-gutter.scss
  src/styles/editor/columns-responsive.scss
  src/styles/editor/columns.scss
  src/styles/legacy/margin.scss
  src/styles/style/columns-gutter.scss
  src/styles/style/columns-responsive.scss
  src/styles/style/columns.scss
  src/styles/style/has-margin.scss
  src/styles/style/has-padding.scss
Labels: [Status] Ready to Merge, [Type] Enhancement

#1526 Fix overwriting existing line height style when none has been set in CoBlocks
  CONTRIBUTORS.md
  src/extensions/typography/apply-style.js
Labels: [Type] Bug

#1527 Enable gallery caption editing when using custom links
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/gallery-stacked/styles/editor.scss
  src/components/block-gallery/styles/editor/_gallery-item-link.scss
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1529 Fix import target for typography controls lodash
  src/extensions/typography/apply-style.js
Labels: [Type] Bug

#1484 Fix fullwidth buttons display issues
  src/extensions/button-controls/styles/editor.scss
  src/extensions/button-controls/styles/style.scss
Labels: [Priority] Low, [Status] Needs Review

#1489 Fix Form block inline toolbar typography controls
  includes/class-coblocks-form.php
Labels: [Type] Bug

#1497 Fix Gallery blocks image links when Lightbox is active
  src/components/block-gallery/gallery-link-settings.js
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1486 Add Lightbox support for Lazy Loading
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Bug

#1473 New Layout Selector
  .circleci/config.yml
  .dev/tests/cypress/helpers.js
  .dev/tests/phpunit/src/extensions/layout-selector/test-index.php
  class-coblocks.php
  docs/hooks/layout-selector.md
  includes/class-coblocks-settings.php
  src/blocks.js
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-store.js
  src/extensions/coblocks-settings/coblocks-settings.cypress.js
  src/extensions/layout-selector/editor.scss
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/index.php
  src/extensions/layout-selector/store.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1520 Social profiles: Open links in new tab
  src/blocks/social-profiles/block.json
  src/blocks/social-profiles/index.php
  src/blocks/social-profiles/inspector.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1534 Fix Services innerBlock based on column count
  src/blocks/services/edit.js
  src/blocks/services/test/services.cypress.js
Labels: [Type] Bug

#1532 Fix primary/secondary buttons in custom components with Gutenberg active
  src/components/responsive-tabs-control/index.js
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/size-control/index.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug, [Type] Gutenberg

#1540 Remove reference to coblocks.com
  .circleci/config.yml
  README.md
  class-coblocks.php
  readme.txt
  src/blocks/form/deprecatedTemplates/layouts.js
Labels: [Type] Enhancement

#1541 Remove selected block outline from Shape Divider block
  src/blocks/shape-divider/styles/editor.scss
Labels: [Type] Bug, [Type] Gutenberg

#1543 Fix editor performance relating to advanced margins
  src/extensions/advanced-controls/index.js
Labels: [Type] Bug

#1544 Add proper styling for the DimensionsControl in Gutenberg 8.3+
  src/components/dimensions-control/index.js
  src/components/dimensions-control/styles/editor.scss
  src/components/responsive-base-control/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1535 Tweak categories in support of new categories within the Gutenberg plugin
  src/blocks/gallery-carousel/block.json
  src/blocks/gallery-carousel/index.js
  src/blocks/gallery-collage/block.json
  src/blocks/gallery-collage/index.js
  src/blocks/gallery-masonry/block.json
  src/blocks/gallery-masonry/index.js
  src/blocks/gallery-offset/block.json
  src/blocks/gallery-offset/index.js
  src/blocks/gallery-stacked/block.json
  src/blocks/gallery-stacked/index.js
  src/blocks/gif/block.json
  src/blocks/gif/index.js
  src/blocks/gist/block.json
  src/blocks/gist/index.js
  src/blocks/icon/block.json
  src/blocks/icon/index.js
  src/blocks/share/block.json
  src/blocks/share/index.js
  src/blocks/social-profiles/block.json
  src/blocks/social-profiles/index.js
  src/utils/block-helpers.js
Labels: [Priority] Low, [Status] In Progress, [Type] Enhancement, [Type] Gutenberg

#1546 Update the services block selected state
  src/blocks/services/service/styles/editor.scss
Labels: [Status] Needs Review, [Type] Enhancement

#1545 Fix Accordion children block appender
  src/blocks/accordion/edit.js
  src/blocks/accordion/test/accordion.cypress.js
Labels: [Type] Bug

#1547 Fix Posts and PostCarousel validation error
  src/blocks/post-carousel/inspector.js
  src/blocks/posts/inspector.js
Labels: [Type] Bug

#1533 Fix gallery captions and custom links disappearing
  src/components/block-gallery/gallery-placeholder.js
Labels: [Type] Bug

#1548 Improve consistency of advanced margin propagation
  src/extensions/advanced-controls/index.js
Labels: [Type] Bug

#1542 Fix Map block API features
  src/blocks/map/edit.js
  src/blocks/map/styles/editor.scss
  src/js/coblocks-google-maps.js
Labels: [Type] Bug

#1552 Fix unit tests by importing getCategories
  src/utils/block-helpers.js
Labels: [Priority] Critical, [Type] Bug

#1553 Use React hooks to improve Advanced Margins feature
  src/extensions/advanced-controls/index.js
Labels: [Priority] High, [Status] Needs Review, [Type] Code Quality
