Repository godaddy-wordpress/coblocks, pull requests merged in 2020-04, with the labels that each got.

#1390 wp_json_encode needs an integer
  src/blocks/events/index.php
  src/blocks/post-carousel/index.php
Labels: [Priority] Low, [Type] Code Quality

#1388 Validate Composer configuration
  .circleci/config.yml
  composer.json
Labels: [Priority] Low, [Type] Enhancement

#1445 Unify gutterOption values and remove duplicate code
  src/blocks/events/index.php
  src/blocks/features/inspector.js
  src/blocks/gallery-collage/inspector.js
  src/blocks/gallery-offset/inspector.js
  src/blocks/posts/inspector.js
  src/blocks/row/inspector.js
  src/blocks/services/inspector.js
  src/utils/gutter-options.js
Labels: [Status] Ready to Merge, [Type] Code Quality

#1444 Settings: Return instance on register
  includes/class-coblocks-accordion-ie-support.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-font-loader.php
  includes/class-coblocks-generated-styles.php
  includes/class-coblocks-google-map-block.php
  includes/class-coblocks-register-blocks.php
  includes/class-coblocks-settings.php
Labels: [Status] Ready to Merge, [Type] Enhancement

#1430 Fix Icon block spacing when using custom links
  src/blocks/icon/styles/style.scss
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1442 Fix Map block placeholder styles
  src/blocks/map/edit.js
  src/blocks/map/styles/editor.scss
Labels: [Status] Ready to Merge, [Type] Bug

#1451 Do not register if coblocksSettings is undefined
  src/extensions/coblocks-settings/index.js
Labels: [Type] Bug

#1433 Improve Share block UX
  cypress.json
  package-lock.json
  package.json
  src/blocks/share/edit.js
  src/blocks/share/styles/editor.scss
  src/blocks/share/test/share.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1443 Fix duplicate classes with Posts block
  .dev/tests/cypress/helpers.js
  .dev/tests/phpunit/src/blocks/posts/test-index.php
  cypress.json
  package-lock.json
  src/blocks/posts/edit.js
  src/blocks/posts/index.php
  src/blocks/posts/test/posts.cypress.js
Labels: [Status] Ready to Merge, [Type] Bug

#1437 Introduce Vertical Alignment controls to Row block.
  src/blocks/row/block.json
  src/blocks/row/column/block.json
  src/blocks/row/column/controls.js
  src/blocks/row/column/edit.js
  src/blocks/row/column/save.js
  src/blocks/row/column/test/deprecated.spec.js
  src/blocks/row/controls.js
  src/blocks/row/edit.js
  src/blocks/row/save.js
  src/blocks/row/styles/style.scss
  src/blocks/row/test/deprecated.spec.js
  src/blocks/row/test/row.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1450 Add proper example to the Pricing Table block
  src/blocks/pricing-table/example.js
  src/blocks/pricing-table/index.js
Labels: [Priority] High, [Status] Needs Review

#1456 Fix Accordion block display across browsers
  src/blocks/accordion/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug

#1458 Handle Accordion block open state when selected
  src/blocks/accordion/accordion-item/edit.js
Labels: [Status] Needs Review, [Type] Enhancement

#1459 Fix Row block alignment bug with Go theme
  src/blocks/row/column/test/column.cypress.js
  src/blocks/row/styles/editor.scss
Labels: [Type] Bug

#1447 Properly scope the date picker to prevent conflicts
  src/js/coblocks-datepicker.js
  src/styles/style/datepicker.scss
Labels: [Priority] Low

#1461 Fixed checkbox icon
  dist/images/list/checkbox-rounded.svg
Labels: First-time Contributor, [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1462 Add passatgt as a contributor 🎉
  CONTRIBUTORS.md
Labels: [Priority] Low, [Status] Ready to Merge

#1452 Deploy canary build to wpnux
  .circleci/config.yml
Labels: [Priority] High, [Status] Needs Review, [Type] Tooling

#1429 Refactor CoBlocks Lightbox to remove jQuery
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Code Quality

#1464 Update WP.org FAQs
  readme.txt
Labels: [Type] Docs

#1467 Fix form submissions not functioning properly
  includes/class-coblocks-form.php
Labels: [Priority] Critical, [Type] Bug

#1440 Use columns/gutter utilities on the Pricing Table block
  src/blocks/alert/deprecated.js
  src/blocks/pricing-table/block.json
  src/blocks/pricing-table/deprecated.js
  src/blocks/pricing-table/edit.js
  src/blocks/pricing-table/inspector.js
  src/blocks/pricing-table/save.js
  src/blocks/pricing-table/styles/editor.scss
  src/blocks/pricing-table/styles/legacy.scss
  src/blocks/pricing-table/styles/style.scss
  src/blocks/pricing-table/test/__snapshots__/save.spec.js.snap
  src/blocks/pricing-table/test/deprecated.spec.js
  src/blocks/row/column/deprecated.js
  src/blocks/services/styles/editor.scss
  src/styles/editor/columns-gutter.scss
  src/styles/editor/columns.scss
  src/styles/editor/core/_breakpoints.scss
  src/styles/editor/core/_mixins.scss
  src/styles/style/columns-gutter.scss
  src/styles/style/columns.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Enhancement

#1448 Improve keywords for icons
  src/blocks/icon/svgs.js
Labels: [Priority] High, [Status] Needs Review, [Type] i18n

#1463 Propagate alignment to Hero block inner buttons
  src/blocks/hero/edit.js
  src/components/grid-control/index.js
  src/js/deprecations/deprecate-coblocks-buttons.js
Labels: [Status] Needs Review, [Type] Enhancement

#1469 Try removing masonry transition
  src/js/coblocks-masonry.js
Labels: [Priority] Low, [Status] Needs Review

#1468 Add form block e2e test to confirm emails are being sent
  .circleci/config.yml
  .dev/bin/install-mailhog.sh
  .dev/mailhog.php
  src/blocks/form/test/form.cypress.js
Labels: [Type] Enhancement

#1465 Allow core/shortcode in the Pricing Table block
  src/blocks/pricing-table/pricing-table-item/edit.js
  src/blocks/pricing-table/pricing-table-item/styles/editor.scss
  src/blocks/pricing-table/styles/editor.scss
Labels: [Status] Needs Review, [Type] Enhancement

#1455 Only load front end CSS when it is needed
  .dev/tests/phpunit/includes/test-coblocks-block-assets.php
  .dev/tests/phpunit/includes/test-coblocks-generated-styles.php
  CONTRIBUTORS.md
  includes/class-coblocks-block-assets.php
Labels: [Priority] Low, [Status] In Progress, [Type] Enhancement
