Repository godaddy-wordpress/coblocks, pull requests merged in 2020-02, with the labels that each got.

#1338 CI: Fix E2E job not finding WP-CLI binary
  .circleci/config.yml
  .dev/bin/setup-test-specs.sh
  .dev/tests/cypress/constants.js
  .dev/tests/cypress/helpers.js
  .dev/tests/cypress/readme.md
  .gitignore
  cypress.json
Labels: [Priority] Critical, [Status] Needs Review, [Type] Bug, [Type] Tooling

#1335 Ensure hero block custom classes are applied in the editor
  .circleci/config.yml
  src/blocks/hero/edit.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#1330 Add consistent labels + labeler action
  .github/labels.yml
  .github/workflows/labeler.yml
Labels: [Priority] Low, [Type] Maintenance

#1334 Stack buttons block on mobile
  src/blocks/buttons/styles/style.scss
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1341 Reinitialize Flickity carousel when used inside an Accordion block
  .dev/config/webpack.config.js
  includes/class-coblocks-block-assets.php
  src/js/coblocks-accordion-carousel.js
Labels: [Status] Needs Review, [Type] Bug

#1343 Use new banner on the README
  README.md
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Maintenance

#1342 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
Labels: [Priority] Low, [Type] Maintenance

#1337 Don't translate date strings in the iCal parser
  includes/ical-parser/class-coblocks-ical.php
Labels: [Priority] High, [Status] Needs Review, [Type] Bug, [Type] i18n

#1333 Skip empty values in generated styles from the DimensionsControl
  includes/class-coblocks-generated-styles.php
Labels: [Priority] Low, [Status] Needs Review, [Type] Bug

#1329 Fix block toolbar interactions within the Hero block
  src/blocks/hero/styles/editor.scss
Labels: [Priority] High, [Status] Ready to Merge, [Type] Bug

#1345 Fix pull_request_template file name
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: [Type] Maintenance

#1346 Move pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Type] Maintenance

#1325 Add gutter support to Posts block
  .dev/tests/cypress/helpers.js
  cypress.json
  src/blocks/posts/block.json
  src/blocks/posts/edit.js
  src/blocks/posts/index.php
  src/blocks/posts/inspector.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1323 Replace older ButtonGroup controls with OptionSelectorControl
  src/blocks/features/inspector.js
  src/blocks/gallery-offset/inspector.js
  src/blocks/row/inspector.js
  src/blocks/services/inspector.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Enhancement

#1347 Fix Gluten Free attribute display on Food & Drinks block
  src/blocks/food-and-drinks/food-item/styles/style.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1351 Fix typo in Stacked Gallery description
  src/blocks/gallery-stacked/index.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Bug

#1313 Introduce CoBlocks settings panel
  class-coblocks.php
  includes/class-coblocks-settings.php
  src/blocks.js
  src/components/typography-controls/index.js
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-store.js
  src/extensions/coblocks-settings/index.js
  src/extensions/coblocks-settings/section.js
  src/extensions/coblocks-settings/styles/style.scss
Labels: [Priority] High, [Status] Needs Review, [Type] Enhancement

#1344 Tweak attributes for consistency
  .stylelintignore
  src/blocks/events/edit.js
  src/blocks/events/event-item/edit.js
  src/blocks/events/event-item/save.js
  src/blocks/features/inspector.js
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/inspector.js
  src/blocks/food-and-drinks/food-item/save.js
  src/blocks/food-and-drinks/inspector.js
  src/blocks/logos/inspector.js
  src/blocks/posts/edit.js
  src/blocks/posts/inspector.js
  src/blocks/row/edit.js
  src/blocks/row/styles/editor.scss
  src/blocks/services/edit.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Code Quality

#1320 Fix Gallery custom link persistence
  src/components/block-gallery/gallery-placeholder.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1315 Add ability to style Post block featured images
  src/blocks/posts/block.json
  src/blocks/posts/edit.js
  src/blocks/posts/index.php
  src/blocks/posts/inspector.js
  src/blocks/posts/styles/editor.scss
  src/blocks/posts/styles/style.scss
  src/blocks/posts/test/posts.cypress.js
  src/components/option-selector-control/index.js
Labels: [Priority] High, [Status] Needs Review, [Type] Enhancement

#1353 Fix navigation arrow position on Carousel block
  src/blocks/gallery-carousel/styles/style.scss
Labels: [Priority] High, [Status] Needs Review, [Type] Design

#1354 Updating the readme for 1.21.0
  .circleci/config.yml
  changelog.txt
  readme.txt
Labels: [Type] Docs

#1352 Move HeadingToolbar controls to block toolbar
  .dev/tests/cypress/helpers.js
  src/blocks/features/controls.js
  src/blocks/features/edit.js
  src/blocks/features/inspector.js
  src/blocks/features/test/features.cypress.js
  src/blocks/services/edit.js
  src/blocks/services/inspector.js
  src/blocks/services/test/services.cypress.js
  src/components/heading-toolbar/icon.js
  src/components/heading-toolbar/index.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement, [Type] Needs Tests

#1355 Implement blockVariationPicker with Form block
  src/blocks/form/edit.js
  src/blocks/form/index.js
  src/blocks/form/variations.js
Labels: [Status] Needs Review, [Type] Bug, [Type] Gutenberg

#1368 Add one column option to the Row block
  src/blocks/row/edit.js
  src/blocks/row/test/row.cypress.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1366 Add docs for settings panel hooks
  CONTRIBUTORS.md
  docs/hooks/settings-panel.md
Labels: First-time Contributor, [Status] Ready to Merge, [Type] Docs

#1358 Introduce Black & white and Grayscale Logos block styles
  src/blocks/logos/block.json
  src/blocks/logos/controls.js
  src/blocks/logos/deprecated.js
  src/blocks/logos/edit.js
  src/blocks/logos/index.js
  src/blocks/logos/inspector.js
  src/blocks/logos/logos.js
  src/blocks/logos/save.js
  src/blocks/logos/styles/editor.scss
  src/blocks/logos/styles/style.scss
  src/blocks/logos/test/__snapshots__/save.spec.js.snap
  src/blocks/logos/test/deprecated.spec.js
  src/blocks/logos/test/logos.cypress.js
  src/blocks/logos/test/save.spec.js
Labels: [Status] Ready to Merge, [Type] Bug, [Type] Enhancement

#1348 Introduce Jest tests [Phase 4]
  src/blocks/features/feature/test/__snapshots__/save.spec.js.snap
  src/blocks/features/feature/test/save.spec.js
  src/blocks/features/test/__snapshots__/save.spec.js.snap
  src/blocks/features/test/save.spec.js
  src/blocks/food-and-drinks/food-item/test/__snapshots__/save.spec.js.snap
  src/blocks/food-and-drinks/food-item/test/save.spec.js
  src/blocks/food-and-drinks/test/__snapshots__/save.spec.js.snap
  src/blocks/food-and-drinks/test/save.spec.js
  src/blocks/pricing-table/pricing-table-item/test/__snapshots__/save.spec.js.snap
  src/blocks/pricing-table/pricing-table-item/test/save.spec.js
  src/blocks/pricing-table/test/__snapshots__/save.spec.js.snap
  src/blocks/pricing-table/test/save.spec.js
  src/blocks/row/column/test/__snapshots__/save.spec.js.snap
  src/blocks/row/column/test/save.spec.js
  src/blocks/row/test/__snapshots__/save.spec.js.snap
  src/blocks/row/test/save.spec.js
  src/blocks/services/service/test/__snapshots__/save.spec.js.snap
  src/blocks/services/service/test/save.spec.js
  src/blocks/services/test/__snapshots__/save.spec.js.snap
  src/blocks/services/test/save.spec.js
Labels: [Status] Needs Review, [Type] Tests

#1357 Introduce Jest tests [Phase 3]
  .circleci/config.yml
  src/blocks/gif/test/__snapshots__/save.spec.js.snap
  src/blocks/gif/test/save.spec.js
  src/blocks/gist/test/__snapshots__/save.spec.js.snap
  src/blocks/gist/test/save.spec.js
  src/blocks/hero/test/__snapshots__/save.spec.js.snap
  src/blocks/hero/test/save.spec.js
  src/blocks/logos/test/__snapshots__/save.spec.js.snap
  src/blocks/logos/test/save.spec.js
  src/blocks/map/test/__snapshots__/save.spec.js.snap
  src/blocks/map/test/save.spec.js
  src/blocks/media-card/test/__snapshots__/save.spec.js.snap
  src/blocks/media-card/test/save.spec.js
  src/blocks/post-carousel/test/__snapshots__/save.spec.js.snap
  src/blocks/post-carousel/test/save.spec.js
  src/blocks/posts/test/__snapshots__/save.spec.js.snap
  src/blocks/posts/test/save.spec.js
Labels: [Status] Needs Review, [Type] Tests

#1379 Stop unconditionally enqueuing slick.js
  includes/class-coblocks-block-assets.php
  src/blocks/events/index.php
Labels: [Priority] High, [Status] Needs Review
