Repository godaddy-wordpress/coblocks, pull requests merged in 2020-09, with the labels that each got.

#1605 Add styles to Media & Text block
  src/blocks.js
  src/common.scss
  src/extensions/media-text-styles/index.js
  src/extensions/media-text-styles/styles/style.scss
  src/extensions/media-text-styles/test/media-text-styles.cypress.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement, [Type] Gutenberg

#1638 Introduce Posts and Post Carousel block deprecations
  src/blocks/post-carousel/block.json
  src/blocks/post-carousel/deprecated.js
  src/blocks/post-carousel/index.js
  src/blocks/post-carousel/index.php
  src/blocks/posts/block.json
  src/blocks/posts/deprecated.js
  src/blocks/posts/index.js
  src/blocks/posts/index.php
Labels: [Priority] High, [Type] Bug

#1656 Remove arrows from lightbox in single image galleries
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Enhancement

#1657 Fix cursor hover state on offset/collage blocks
  src/blocks/gallery-masonry/styles/editor.scss
  src/extensions/lightbox-controls/styles/editor.scss
Labels: [Type] Enhancement

#1655 Remove box shadow from selected form field
  src/blocks/form/styles/editor.scss
Labels: [Priority] Low, [Status] Ready to Merge

#1647 Introduce ability to define a custom 'Success Message' setting in the form block
  .dev/tests/phpunit/includes/test-coblocks-form.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-form.php
  src/blocks/form/edit.js
  src/blocks/form/index.js
  src/blocks/form/test/form.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1581 Layouts as Custom Post Type
  class-coblocks.php
  composer.lock
  includes/class-block-patterns.php
  includes/traits/trait-coblocks-singleton.php
  src/extensions/layout-selector/index.js
  yarn.lock
Labels: [Status] Needs Review, [Type] Enhancement

#1659 Introduce custom block patterns saved as a CPT.
  includes/class-block-patterns.php
  src/blocks.js
  src/extensions/block-patterns/index.js
  src/extensions/block-patterns/modal.js
  src/extensions/block-patterns/styles/style.scss
Labels: [Type] Enhancement

#1660 Fix variation titles for Row and Form blocks
  src/blocks/form/variations.js
  src/blocks/row/variations.js
Labels: [Priority] Low, [Status] Needs Review

#1662 Minor icon fixes
  src/blocks/accordion/accordion-item/controls.js
  src/blocks/row/column/icon.js
  src/blocks/row/column/index.js
  src/blocks/row/edit.js
  src/blocks/row/index.js
Labels: [Priority] Low, [Status] Needs Review

#1661 Add support for __experimentalCaptureToolbars
  src/blocks/accordion/accordion-item/edit.js
  src/blocks/accordion/edit.js
  src/blocks/author/edit.js
  src/blocks/features/edit.js
  src/blocks/features/feature/edit.js
  src/blocks/food-and-drinks/edit.js
  src/blocks/form/edit.js
  src/blocks/hero/edit.js
  src/blocks/media-card/edit.js
  src/blocks/pricing-table/edit.js
  src/blocks/services/edit.js
Labels: [Priority] Low, [Type] Enhancement

#1643 Fix required form radio/checkbox fields
  .dev/config/webpack.config.js
  .dev/tests/phpunit/includes/test-coblocks-form.php
  .dev/tests/phpunit/test-class-coblocks.php
  docs/hooks/forms-block.md
  includes/class-coblocks-form.php
  src/blocks/form/styles/style.scss
  src/js/coblocks-checkbox-required.js
Labels: [Status] Needs Review, [Type] Enhancement

#1671 Pricing Table: Use ToolbarGroup to render controls correctly
  src/blocks/pricing-table/controls.js
Labels: [Status] Ready to Merge, [Type] Bug, [Type] Gutenberg

#1674 Add @WunderBart as a contributor 🎉
  CONTRIBUTORS.md
Labels: [Priority] Low, [Status] Needs Review

#1669 Fix editor crash when running CoBlocks and WordPress 5.4.2
  includes/class-block-patterns.php
  src/extensions/block-patterns/index.js
Labels: [Priority] Critical, [Type] Bug

#1677 Fix required checkbox/radio hidden message escaped markup
  includes/class-coblocks-form.php
Labels: [Type] Bug

#1675 Prevent layout selector on posts saved as a draft
  .circleci/config.yml
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1676 Add form field transformations
  .dev/tests/jest/helpers.js
  src/blocks/form/fields/checkbox/index.js
  src/blocks/form/fields/checkbox/test/transforms.spec.js
  src/blocks/form/fields/checkbox/transforms.js
  src/blocks/form/fields/date/index.js
  src/blocks/form/fields/date/test/transforms.spec.js
  src/blocks/form/fields/date/transforms.js
  src/blocks/form/fields/hidden/index.js
  src/blocks/form/fields/hidden/test/transforms.spec.js
  src/blocks/form/fields/hidden/transforms.js
  src/blocks/form/fields/name/index.js
  src/blocks/form/fields/name/test/transforms.spec.js
  src/blocks/form/fields/name/transforms.js
  src/blocks/form/fields/phone/index.js
  src/blocks/form/fields/phone/test/transforms.spec.js
  src/blocks/form/fields/phone/transforms.js
  src/blocks/form/fields/radio/index.js
  src/blocks/form/fields/radio/test/transforms.spec.js
  src/blocks/form/fields/radio/transforms.js
  src/blocks/form/fields/select/index.js
  src/blocks/form/fields/select/test/transforms.spec.js
  src/blocks/form/fields/select/transforms.js
  src/blocks/form/fields/text/index.js
  src/blocks/form/fields/text/test/transforms.spec.js
  src/blocks/form/fields/text/transforms.js
  src/blocks/form/fields/textarea/index.js
  src/blocks/form/fields/textarea/test/transforms.spec.js
  src/blocks/form/fields/textarea/transforms.js
  src/blocks/form/fields/website/index.js
  src/blocks/form/fields/website/test/transforms.spec.js
  src/blocks/form/fields/website/transforms.js
Labels: [Status] Needs Review, [Type] Enhancement

#1680 Transform Form fields with with proper labels
  src/blocks/form/fields/checkbox/transforms.js
  src/blocks/form/fields/date/transforms.js
  src/blocks/form/fields/hidden/transforms.js
  src/blocks/form/fields/name/transforms.js
  src/blocks/form/fields/phone/transforms.js
  src/blocks/form/fields/radio/transforms.js
  src/blocks/form/fields/select/transforms.js
  src/blocks/form/fields/text/transforms.js
  src/blocks/form/fields/textarea/transforms.js
  src/blocks/form/fields/website/transforms.js
Labels: [Priority] High, [Status] Needs Review

#1679 Collage block: Add caption margin zero
  src/blocks/gallery-collage/styles/style.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1681 Add Jon Surrell as a contributor 🎉
  CONTRIBUTORS.md
Labels: [Priority] Low

#1673 HeadingToolbar: Use ToolbarGroup to render controls correctly
  src/components/heading-toolbar/index.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Gutenberg

#1646 Introduce From block label color controls
  .dev/tests/cypress/helpers.js
  class-coblocks.php
  includes/class-coblocks-form.php
  src/blocks.js
  src/blocks/form/edit.js
  src/blocks/form/fields/checkbox/index.js
  src/blocks/form/fields/date/edit.js
  src/blocks/form/fields/date/index.js
  src/blocks/form/fields/email/edit.js
  src/blocks/form/fields/email/index.js
  src/blocks/form/fields/field-label.js
  src/blocks/form/fields/field.js
  src/blocks/form/fields/helpers.js
  src/blocks/form/fields/multi-field.js
  src/blocks/form/fields/name/edit.js
  src/blocks/form/fields/name/index.js
  src/blocks/form/fields/phone/edit.js
  src/blocks/form/fields/phone/index.js
  src/blocks/form/fields/radio/index.js
  src/blocks/form/fields/select/index.js
  src/blocks/form/fields/text/edit.js
  src/blocks/form/fields/text/index.js
  src/blocks/form/fields/textarea/edit.js
  src/blocks/form/fields/textarea/index.js
  src/blocks/form/fields/website/edit.js
  src/blocks/form/fields/website/index.js
  src/blocks/form/index.js
  src/blocks/form/test/form.cypress.js
  src/components/form-label-colors/index.js
  src/components/form-label-colors/label-color-control.js
  src/components/form-label-colors/label-color-wrapper.js
  src/components/form-label-colors/label-color-wrapper.php
Labels: [Status] Needs Review, [Type] Enhancement

#1683 Tweak Form label color controls
  src/components/form-label-colors/label-color-control.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1685 Resolve PHPCS errors on main
  includes/class-coblocks-form.php
  src/components/form-label-colors/label-color-wrapper.php
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1686 Resolve errors around icon imports
  src/blocks/gallery-carousel/edit.js
Labels: [Priority] Critical, [Type] Bug

#1642 Introduce improved E2E testing for layouts and image downloader
  .dev/tests/cypress/helpers.js
  .dev/tests/cypress/support/commands.js
  .eslintignore
  cypress.json
  languages/coblocks.pot
  languages/da_DK.json
  languages/de_DE.json
  languages/el.json
  languages/es_ES.json
  languages/es_MX.json
  languages/fi.json
  languages/fr_FR.json
  languages/hi_IN.json
  languages/id_ID.json
  languages/it_IT.json
  languages/ja.json
  languages/ko_KR.json
  languages/nb_NO.json
  languages/nl_NL.json
  languages/pl_PL.json
  languages/pt_BR.json
  languages/pt_PT.json
  languages/ru_RU.json
  languages/sv_SE.json
  languages/th.json
  languages/tr_TR.json
  languages/uk.json
  languages/vi.json
  languages/zh_CN.json
  languages/zh_TW.json
  package.json
  src/blocks/gallery-carousel/edit.js
  src/extensions/layout-selector/test/cypress-layouts.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  yarn.lock
Labels: [Status] Needs Review, [Type] Tests

#1607 Download remote images used in layouts
  .dev/tests/cypress/helpers.js
  .dev/tests/cypress/support/commands.js
  .eslintignore
  cypress.json
  package.json
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/test/cypress-layouts.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  yarn.lock
Labels: [Status] Needs Review, [Type] Enhancement

#1687 Migrate gallery/image controls to use core styles
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/styles/editor.scss
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/services/service/edit.js
  src/blocks/services/service/styles/editor.scss
  src/components/block-gallery/gallery-image.js
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/components/block-gallery/styles/editor/_radius.scss
  src/styles/editor/is-transient.scss
Labels: [Status] In Progress

#1672 Remove unnecessary SCSS variables and use @wordpress/base-styles instead
  .dev/tests/cypress/helpers.js
  src/blocks/author/styles/editor.scss
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/food-and-drinks/styles/editor.scss
  src/blocks/form/styles/editor.scss
  src/blocks/form/styles/theme.scss
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/gallery-stacked/styles/style.scss
  src/blocks/gist/styles/editor.scss
  src/blocks/gist/styles/style.scss
  src/blocks/icon/styles/editor.scss
  src/blocks/map/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/blocks/row/styles/style.scss
  src/blocks/services/service/styles/editor.scss
  src/common.scss
  src/components/background/styles/editor.scss
  src/components/block-gallery/styles/editor/_flickity-arrows.scss
  src/components/block-gallery/styles/editor/_gallery-item-link.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/components/block-gallery/styles/style.scss
  src/components/block-gallery/styles/style/_core-themes.scss
  src/components/block-gallery/styles/style/_lightbox.scss
  src/components/dimensions-control/styles/editor.scss
  src/components/responsive-base-control/styles/editor.scss
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/typography-controls/styles/editor.scss
  src/extensions/block-patterns/styles/style.scss
  src/extensions/coblocks-settings/styles/style.scss
  src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
  src/extensions/layout-selector/editor.scss
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/media-text-styles/styles/style.scss
  src/styles/editor/core/_breakpoints.scss
  src/styles/editor/core/_colors.scss
  src/styles/editor/core/_mixins.scss
  src/styles/editor/core/_variables.scss
  src/styles/mixins.scss
  src/styles/style/tooltips.scss
Labels: [Status] Do Not Merge, [Type] Code Quality

#1689 Update icons to utilize @wordpress/icons edit icon
  src/blocks/author/controls.js
  src/blocks/events/edit.js
  src/blocks/gist/controls.js
  src/blocks/logos/controls.js
  src/blocks/map/controls.js
  src/blocks/post-carousel/edit.js
  src/blocks/posts/edit.js
Labels: [Priority] Low

#1696 Add styles to fix appearance of Gallery blocks
  package.json
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-masonry/styles/style.scss
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/styles/editor.scss
  src/blocks/gallery-stacked/styles/editor.scss
  src/components/block-gallery/gallery-image.js
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  yarn.lock
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1697 Enhance social block style previews
  src/blocks/share/styles/editor.scss
Labels: [Priority] High, [Type] Bug, [Type] Design

#1695 Fix appearance of Row block column spacing controls
  src/blocks/row/controls.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1694 Enhance Map block placeholder with new styles
  src/blocks/map/edit.js
  src/blocks/map/styles/editor.scss
  src/blocks/map/test/map.cypress.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Design

#1691 Update/gallery innerblocks arrow orientation
  src/blocks/services/edit.js
  src/blocks/services/test/services.cypress.js
Labels: [Type] Enhancement
