Repository godaddy-wordpress/coblocks, pull requests merged in 2020-07, with the labels that each got.

#1562 Fix multi-selected layout issue
  src/extensions/layout-selector/editor.scss
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Bug

#1556 Introduce Padding Controls extension to core/group block
  src/blocks.js
  src/extensions/padding-controls/index.js
  src/extensions/padding-controls/padding-controls.cypress.js
  src/styles/style/has-padding.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1515 Ensure extensions are applied properly to blocks
  src/blocks/hero/edit.js
  src/extensions/advanced-controls/index.js
  src/extensions/button-controls/index.js
  src/extensions/typography/index.js
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1565 Accordion block save function tests
  src/blocks/accordion/accordion-item/test/__snapshots__/save.spec.js.snap
  src/blocks/accordion/accordion-item/test/save.spec.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Code Quality, [Type] Tests

#1566 Allow HTML formatted text within Lightbox captions
  CONTRIBUTORS.md
  src/js/coblocks-lightbox.js
Labels: First-time Contributor, [Status] Needs Review, [Type] Bug

#1557 Introduce Lightbox Controls extension to core/gallery and core/image blocks
  includes/class-coblocks-block-assets.php
  src/blocks.js
  src/components/block-gallery/styles/style/_lightbox.scss
  src/extensions/lightbox-controls/index.js
  src/extensions/lightbox-controls/lightbox-controls.cypress.js
  src/extensions/lightbox-controls/styles/style.scss
  src/extensions/replace-image/style.scss
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Enhancement

#1567 Allow closing of Lightbox with keyboard Esc key
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Bug

#1570 Remove Rich from CODEOWNERS
  .github/CODEOWNERS
Labels: [Priority] Low, [Type] Maintenance

#1571 Detect modified code in extensions when setting up test specs
  .dev/bin/setup-test-specs.sh
  src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
  src/extensions/colors/test/apply-style.spec.js
  src/extensions/colors/test/classes.spec.js
  src/extensions/colors/test/transform.spec.js
  src/extensions/lightbox-controls/test/lightbox-controls.cypress.js
  src/extensions/padding-controls/test/padding-controls.cypress.js
  src/extensions/replace-image/test/remove-image.cypress.js
  src/extensions/typography/test/apply-style.spec.js
Labels: [Priority] High, [Status] Needs Review, [Type] Code Quality, [Type] Tests, [Type] Tooling

#1568 Fix errors in hero block resize
  src/blocks/hero/edit.js
Labels: [Priority] High, [Status] Ready to Merge

#1575 Fix Click to Tweet inline toolbar via SVG
  src/blocks/click-to-tweet/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Gutenberg

#1576 Fix Post and Post Carousel blocks compatibility across versions
  src/blocks/post-carousel/block.json
  src/blocks/post-carousel/edit.js
  src/blocks/post-carousel/inspector.js
  src/blocks/posts/block.json
  src/blocks/posts/edit.js
  src/blocks/posts/inspector.js
Labels: [Status] Ready to Merge, [Type] Bug

#1573 Enable extensibility of Settings panel using SlotFill component
  docs/hooks/settings-panel.md
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-slot.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Enhancement

#1583 Documentation for new releases
  docs/contributors/release.md
Labels: [Status] Needs Review, [Type] Docs

#1584 Remove editor list styles from gallery blocks
  src/blocks/gallery-collage/styles/style.scss
  src/blocks/gallery-masonry/styles/style.scss
  src/blocks/gallery-offset/styles/style.scss
  src/blocks/gallery-stacked/styles/style.scss
Labels: [Priority] High, [Status] Needs Review

#1588 Update the HeadingLevel Icon to match Gutenberg
  src/components/heading-toolbar/icon.js
Labels: [Type] Design

#1592 Fix lightbox extension display for core blocks
  src/extensions/lightbox-controls/styles/style.scss
Labels: [Priority] High, [Type] Bug

#1593 Update Icons across blocks and utilities
  src/blocks/accordion/accordion-item/icon.js
  src/blocks/accordion/icon.js
  src/blocks/alert/icon.js
  src/blocks/author/icon.js
  src/blocks/click-to-tweet/icon.js
  src/blocks/click-to-tweet/styles/editor.scss
  src/blocks/dynamic-separator/icon.js
  src/blocks/events/icon.js
  src/blocks/features/feature/icon.js
  src/blocks/features/icon.js
  src/blocks/food-and-drinks/food-item/icon.js
  src/blocks/food-and-drinks/icon.js
  src/blocks/form/fields/checkbox/icon.js
  src/blocks/form/fields/date/icon.js
  src/blocks/form/fields/email/icon.js
  src/blocks/form/fields/hidden/icon.js
  src/blocks/form/fields/name/icon.js
  src/blocks/form/fields/phone/icon.js
  src/blocks/form/fields/radio/icon.js
  src/blocks/form/fields/select/icon.js
  src/blocks/form/fields/submit-button/icon.js
  src/blocks/form/fields/text/icon.js
  src/blocks/form/fields/textarea/icon.js
  src/blocks/form/fields/website/icon.js
  src/blocks/form/icon.js
  src/blocks/gallery-carousel/icon.js
  src/blocks/gallery-collage/icon.js
  src/blocks/gallery-masonry/icon.js
  src/blocks/gallery-offset/icon.js
  src/blocks/gallery-stacked/icon.js
  src/blocks/gif/icon.js
  src/blocks/gist/icon.js
  src/blocks/hero/icon.js
  src/blocks/hero/icons.js
  src/blocks/highlight/icon.js
  src/blocks/icon/icon.js
  src/blocks/logos/icon.js
  src/blocks/map/icon.js
  src/blocks/media-card/controls.js
  src/blocks/media-card/icon.js
  src/blocks/media-card/icons.js
  src/blocks/post-carousel/icon.js
  src/blocks/posts/icon.js
  src/blocks/pricing-table/icon.js
  src/blocks/pricing-table/pricing-table-item/icon.js
  src/blocks/row/column/icon.js
  src/blocks/services/icon.js
  src/blocks/services/service/icon.js
  src/blocks/shape-divider/icon.js
  src/blocks/shape-divider/icons.js
  src/blocks/share/icon.js
  src/blocks/social-profiles/icon.js
  src/components/media-filter-control/icons.js
  src/utils/icons.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Enhancement

#1597 Remove core/image support from Crop Settings utility
  src/extensions/image-crop/index.js
Labels: [Status] Needs Review

#1600 Move Gallery UI controls within the interface for consistency
  src/blocks/gallery-carousel/inspector.js
  src/blocks/gallery-collage/inspector.js
Labels: [Status] Needs Review, [Type] Code Quality

#1603 Fix Media Card resize capability
  src/blocks/media-card/styles/editor.scss
Labels: [Status] Ready to Merge, [Type] Bug

#1598 Reference core CSS variables from CoBlocks styles
  src/blocks/food-and-drinks/food-item/styles/editor.scss
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/hero/styles/editor.scss
  src/blocks/media-card/styles/editor.scss
  src/blocks/row/styles/editor.scss
  src/blocks/services/service/styles/editor.scss
  src/blocks/shape-divider/styles/editor.scss
  src/blocks/share/styles/editor.scss
  src/blocks/social-profiles/styles/editor.scss
  src/components/block-gallery/styles/editor/_flickity-arrows.scss
  src/components/block-gallery/styles/editor/_gallery-item-link.scss
  src/components/block-gallery/styles/editor/_gallery-item-menus.scss
  src/components/block-gallery/styles/editor/_gallery-item.scss
  src/components/dimensions-control/styles/editor.scss
  src/components/responsive-tabs-control/styles/editor.scss
  src/components/typography-controls/styles/editor.scss
  src/extensions/layout-selector/editor.scss
Labels: [Priority] Low, [Status] Ready to Merge

#1602 Tweaks to CoBlocks icons descriptions labels and keywords
  src/blocks/click-to-tweet/controls.js
  src/blocks/click-to-tweet/icons.js
  src/blocks/dynamic-separator/index.js
  src/blocks/food-and-drinks/index.js
  src/blocks/gist/index.js
  src/blocks/logos/index.js
  src/utils/icons.js
Labels: [Status] Ready to Merge
