Repository godaddy-wordpress/coblocks, pull requests merged in 2020-03, with the labels that each got.

#1386 Wrap Google fonts in filter
  src/components/font-family/index.js
Labels: [Type] Enhancement

#1393 Persist Accordion block open state when editing a post
  cypress.json
  src/blocks/accordion/accordion-item/edit.js
  src/blocks/accordion/edit.js
  src/blocks/accordion/styles/editor.scss
  src/blocks/accordion/test/accordion.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement

#1380 WordPress 5.4 compatibility changes to CoBlocks
  .dev/tests/cypress/helpers.js
  package-lock.json
  package.json
  src/blocks/alert/test/alert.cypress.js
  src/blocks/author/test/author.cypress.js
  src/blocks/buttons/test/buttons.cypress.js
  src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
  src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
  src/blocks/events/event-item/test/event-item.cypress.js
  src/blocks/events/test/events.cypress.js
  src/blocks/features/feature/test/feature.cypress.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/form/edit.js
  src/blocks/form/test/form.cypress.js
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/styles/editor.scss
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/styles/editor.scss
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/styles/editor.scss
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/blocks/gif/test/gif.cypress.js
  src/blocks/gist/test/gist.cypress.js
  src/blocks/hero/test/hero.cypress.js
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/icon/test/icon.cypress.js
  src/blocks/logos/test/logos.cypress.js
  src/blocks/map/test/map.cypress.js
  src/blocks/media-card/test/media-card.cypress.js
  src/blocks/post-carousel/test/post-carousel.cypress.js
  src/blocks/posts/test/posts.cypress.js
  src/blocks/pricing-table/test/pricing-table.cypress.js
  src/blocks/row/column/test/column.cypress.js
  src/blocks/row/test/row.cypress.js
  src/blocks/shape-divider/test/shape-divider.cypress.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
Labels: [Status] Needs Review, [Type] Bug

#1381 Control Food Item block headings from the parent Food and Drinks block
  src/blocks/food-and-drinks/block.json
  src/blocks/food-and-drinks/controls.js
  src/blocks/food-and-drinks/edit.js
  src/blocks/food-and-drinks/food-item/block.json
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/highlight/test/highlight.cypress.js
  src/components/heading-toolbar/index.js
Labels: [Status] Needs Review, [Type] Enhancement

#1372 Migrate Row block to variations API
  src/blocks/row/column/edit.js
  src/blocks/row/column/inspector.js
  src/blocks/row/controls.js
  src/blocks/row/edit.js
  src/blocks/row/index.js
  src/blocks/row/inspector.js
  src/blocks/row/styles/editor.scss
  src/blocks/row/variations.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1367 Support new block collection functionality in WordPress 5.4
  src/blocks.js
  src/blocks/accordion/accordion-item/block.json
  src/blocks/accordion/block.json
  src/blocks/alert/block.json
  src/blocks/author/block.json
  src/blocks/buttons/block.json
  src/blocks/click-to-tweet/block.json
  src/blocks/dynamic-separator/block.json
  src/blocks/events/block.json
  src/blocks/events/event-item/block.json
  src/blocks/features/block.json
  src/blocks/features/feature/block.json
  src/blocks/food-and-drinks/block.json
  src/blocks/food-and-drinks/food-item/block.json
  src/blocks/form/fields/checkbox/index.js
  src/blocks/form/fields/date/index.js
  src/blocks/form/fields/email/index.js
  src/blocks/form/fields/hidden/index.js
  src/blocks/form/fields/name/index.js
  src/blocks/form/fields/phone/index.js
  src/blocks/form/fields/radio/index.js
  src/blocks/form/fields/select/index.js
  src/blocks/form/fields/textarea/index.js
  src/blocks/form/fields/website/index.js
  src/blocks/form/index.js
  src/blocks/gif/block.json
  src/blocks/gist/block.json
  src/blocks/hero/block.json
  src/blocks/highlight/block.json
  src/blocks/icon/block.json
  src/blocks/logos/block.json
  src/blocks/map/block.json
  src/blocks/media-card/block.json
  src/blocks/post-carousel/block.json
  src/blocks/posts/block.json
  src/blocks/pricing-table/block.json
  src/blocks/pricing-table/pricing-table-item/block.json
  src/blocks/row/block.json
  src/blocks/row/column/block.json
  src/blocks/services/block.json
  src/blocks/services/service/block.json
  src/blocks/shape-divider/block.json
  src/blocks/share/block.json
  src/blocks/social-profiles/block.json
  src/utils/block-category.js
  src/utils/block-helpers.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1396 Specify key file in scp during deployment to staging site
  .circleci/config.yml
Labels: [Type] Tooling

#1400 Fix Row block placeholder spacing
  src/blocks/row/styles/editor.scss
Labels: [Status] Needs Review, [Type] Bug

#1373 Update Form block variable names
  src/blocks/form/edit.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Code Quality

#1398 Introduce 29 new icons into the icon block
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/icon/svgs.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1401 Updating the readme for 1.22.0
  CONTRIBUTORS.md
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, [Type] Maintenance

#1404 Fix selected font family option in the typography controls
  src/components/font-family/index.js
  src/components/typography-controls/index.js
Labels: [Status] Needs Review, [Type] Bug

#1403 Introduce a filter to disable the CoBlocks bundled svg icons
  includes/class-coblocks-block-assets.php
  src/blocks/icon/edit.js
  src/blocks/icon/svgs.js
Labels: [Priority] Low, [Status] Ready to Merge, [Type] Enhancement

#1413 Regenerate package-lock.json file so Jest tests run/pass
  package-lock.json
Labels: [Type] Tooling

#1385 Introduce 'Replace Image' CoBlocks extension
  .dev/tests/cypress/helpers.js
  .eslintignore
  .eslintrc.js
  package.json
  src/blocks.js
  src/blocks/accordion/test/accordion.cypress.js
  src/blocks/alert/test/alert.cypress.js
  src/blocks/author/test/author.cypress.js
  src/blocks/buttons/test/buttons.cypress.js
  src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
  src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
  src/blocks/events/event-item/test/event-item.cypress.js
  src/blocks/events/test/events.cypress.js
  src/blocks/features/feature/test/feature.cypress.js
  src/blocks/features/test/features.cypress.js
  src/blocks/food-and-drinks/food-item/test/food-item.cypress.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/form/test/form.cypress.js
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/blocks/gif/test/gif.cypress.js
  src/blocks/gist/test/gist.cypress.js
  src/blocks/hero/test/hero.cypress.js
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/icon/test/icon.cypress.js
  src/blocks/logos/test/logos.cypress.js
  src/blocks/map/test/map.cypress.js
  src/blocks/media-card/test/media-card.cypress.js
  src/blocks/post-carousel/test/post-carousel.cypress.js
  src/blocks/posts/test/posts.cypress.js
  src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js
  src/blocks/pricing-table/test/pricing-table.cypress.js
  src/blocks/row/column/test/column.cypress.js
  src/blocks/row/test/row.cypress.js
  src/blocks/services/service/test/service.cypress.js
  src/blocks/services/test/services.cypress.js
  src/blocks/shape-divider/test/shape-divider.cypress.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
  src/extensions/replace-image/index.js
  src/extensions/replace-image/remove-image.cypress.js
  src/extensions/replace-image/style.scss
  src/utils/helper.js
Labels: [Status] Needs Review, [Type] Enhancement

#1376 Remove jQuery Phase 1
  src/blocks/form/edit.js
  src/blocks/gif/edit.js
  src/blocks/gif/styles/style.scss
  src/components/crop-settings/index.js
  src/components/crop-settings/original-image.js
  src/extensions/image-crop/index.js
Labels: [Status] Needs Review, [Type] Code Quality

#1406 Fix posts block categories feed setting
  src/blocks/post-carousel/edit.js
  src/blocks/post-carousel/inspector.js
  src/blocks/posts/edit.js
  src/blocks/posts/inspector.js
Labels: [Priority] High, [Status] Ready to Merge, [Type] Bug

#1411 Fix Map block error in editor and refactor wp.api global
  .dev/tests/jest/setup-globals.js
  package-lock.json
  src/blocks/form/edit.js
  src/blocks/map/edit.js
  src/blocks/map/inspector.js
Labels: [Status] Needs Review, [Type] Bug

#1395 Introduce E2E tests for CoBlocks Settings panel
  src/extensions/coblocks-settings/coblocks-settings.cypress.js
Labels: [Status] Needs Review, [Type] Tests

#1417 Add Form block Text field
  includes/class-coblocks-form.php
  src/blocks.js
  src/blocks/form/fields/text/edit.js
  src/blocks/form/fields/text/icon.js
  src/blocks/form/fields/text/index.js
  src/blocks/form/fields/text/test/__snapshots__/save.spec.js.snap
  src/blocks/form/fields/text/test/save.spec.js
Labels: [Priority] High, [Status] Needs Review, [Type] Enhancement

#1418 Add docs for CoBlocks features
  docs/hooks/forms-block.md
  docs/hooks/icons-block.md
  docs/hooks/typography-controls.md
Labels: [Status] Needs Review, [Type] Docs

#1419 Resolve Form block issue with Gutenberg 7.7.1
  src/blocks/form/edit.js
Labels: [Status] Ready to Merge, [Type] Bug, [Type] Gutenberg

#1416 Refactor the form radio and checkbox labels
  .dev/tests/phpunit/includes/test-coblocks-form.php
  includes/class-coblocks-form.php
  src/blocks/form/styles/style.scss
Labels: [Status] Ready to Merge, [Type] Enhancement

#1415 E2E Gauntlet Testing Script
  .dev/bin/README.md
  .dev/bin/e2e-test-gauntlet.sh
  .gitignore
Labels: [Priority] High, [Status] Needs Review, [Type] Code Quality, [Type] Tests, [Type] Tooling

#1409 Show gallery image captions in light box
  src/components/block-gallery/styles/style/_lightbox.scss
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Enhancement

#1407 Clicking captions opens the light box
  src/js/coblocks-lightbox.js
Labels: [Status] Needs Review, [Type] Enhancement

#1422 Updated tested to value for to 5.4
  class-coblocks.php
  package.json
  readme.txt
Labels: [Status] Needs Review, [Type] Docs

#1424 Minor style specificity clean-up
  src/blocks/author/styles/editor.scss
  src/blocks/click-to-tweet/styles/style.scss
  src/blocks/features/styles/editor.scss
  src/blocks/form/styles/editor.scss
  src/blocks/form/styles/theme.scss
  src/blocks/gif/styles/editor.scss
  src/blocks/gif/styles/style.scss
  src/blocks/logos/styles/style.scss
  src/blocks/posts/styles/editor.scss
  src/blocks/pricing-table/styles/editor.scss
Labels: [Priority] High, [Status] Needs Review

#1420 Introduce RTL support
  .dev/config/webpack.config.js
  includes/class-coblocks-block-assets.php
  package-lock.json
  package.json
  src/blocks/media-card/styles/editor.scss
  src/blocks/media-card/styles/style.scss
Labels: [Priority] High, [Status] Ready to Merge, [Type] Enhancement

#1402 Fix image and price toggle behavior on the Food and Drinks block
  src/blocks/food-and-drinks/edit.js
  src/blocks/food-and-drinks/food-item/edit.js
Labels: [Status] Needs Review, [Type] Bug

#1427 1.23.0 changelog and readme updates
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, [Type] Maintenance

#1431 Update canary release CircleCI deploy
  .circleci/config.yml
Labels: [Type] Tooling

#1436 Remove 100% height from gallery carousels on front of site
  src/blocks/gallery-carousel/styles/editor.scss
  src/blocks/gallery-carousel/styles/style.scss
Labels: [Type] Bug

#1389 Fix variable type in coblocks_render_events_block
  src/blocks/events/index.php
Labels: [Priority] Low, [Type] Code Quality

#1375 Introduce cross browser E2E testing
  .circleci/config.yml
  .dev/bin/install-wp-tests.sh
  .dev/tests/cypress/helpers.js
  package-lock.json
  package.json
  src/blocks/accordion/test/accordion.cypress.js
  src/blocks/buttons/test/buttons.cypress.js
  src/blocks/features/feature/test/feature.cypress.js
  src/blocks/features/test/features.cypress.js
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/post-carousel/test/post-carousel.cypress.js
  src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js
  src/blocks/row/test/row.cypress.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement, [Type] Tests
