Repository godaddy-wordpress/coblocks, pull requests merged in 2021-08, with the labels that each got.

#1973 Enable post carousel category relation option to show posts with multiple categories only
  src/blocks/post-carousel/block.json
  src/blocks/post-carousel/edit.js
  src/blocks/post-carousel/index.php
  src/blocks/post-carousel/inspector.js
  src/blocks/posts/block.json
  src/blocks/posts/edit.js
  src/blocks/posts/index.php
  src/blocks/posts/inspector.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1972 Fix `run-all-tests` feature to also run php and css linting
  .circleci/config.yml
  cypress.json
Labels: [Type] Bug, [Status] Needs Review

#1984 Properly save and parse local storage Color Palette values
  src/extensions/colors/settings-modal-control.js
Labels: [Type] Bug

#1991 Add OpenTable block to README
  README.md
  readme.txt
Labels: [Status] Needs Review, [Type] Maintenance
