Repository godaddy-wordpress/coblocks, pull requests merged in 2021-01, with the labels that each got.

#1778 Don't add style to the Cover block placeholder
  src/extensions/cover-styles/styles/style.scss
Labels: [Priority] Low, [Status] Needs Review

#1789 Refactor SizeControl component for improved visual consistency
  src/components/size-control/index.js
Labels: [Type] Design

#1787 Allow aligned images in CoBlocks Lightbox
  .dev/tests/cypress/helpers.js
  src/components/block-gallery/styles/style/_lightbox.scss
  src/extensions/lightbox-controls/test/lightbox-controls.cypress.js
  src/js/coblocks-lightbox.js
Labels: [Type] Bug

#1790 Introduce custom padding controls to core/group block
  src/extensions/padding-controls/index.js
  src/extensions/padding-controls/padding-wrapper.js
  src/extensions/padding-controls/test/padding-controls.cypress.js
  src/styles/style/has-padding.scss
Labels: [Status] Needs Review, [Type] Enhancement

#1794 Ensure layout selector modal is shown only when creating new pages
  src/extensions/layout-selector/store.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
Labels: [Status] Needs Review

#1792 Updates to release process document
  docs/contributors/release.md
Labels: [Status] Needs Review, [Type] Docs

#1798 Fix initial image hidden on carousel initialization
  src/blocks/gallery-carousel/edit.js
Labels: [Status] Needs Review, [Type] Enhancement

#1799 Disable animations when IntersectionObserver is not detected
  src/js/coblocks-animation.js
Labels: [Status] Needs Review

#1803 Try Cypress Changes
  cypress.json
  package.json
  yarn.lock
Labels: [Status] Do Not Merge, [Status] In Progress, [Type] Tests
