Repository godaddy-wordpress/coblocks, pull requests merged in 2021-07, with the labels that each got.

#1923 Introduce WordPress 5.8 compatiblity
  .babelrc
  .dev/bin/install-wp-tests.sh
  .dev/tests/cypress/helpers.js
  includes/class-coblocks-settings.php
  package.json
  src/blocks/author/edit.js
  src/blocks/author/styles/style.scss
  src/blocks/author/test/author.cypress.js
  src/blocks/click-to-tweet/edit.js
  src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
  src/blocks/features/edit.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/blocks/hero/test/hero.cypress.js
  src/blocks/highlight/edit.js
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/icon/svgs.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
  src/components/block-gallery/gallery-image.js
  src/components/media-filter-control/test/media-filter-control.cypress.js
  src/extensions/animation/test/settings-modal-control.cypress.js
  src/extensions/colors/settings-modal-control.js
  src/extensions/colors/test/settings-modal-control.cypress.js
  src/extensions/layout-selector/test/layout-preview.spec.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/media-text-styles/test/media-text-styles.cypress.js
  src/extensions/typography/apply-style.js
  src/extensions/typography/test/settings-modal-control.cypress.js
  src/utils/helper.js
  yarn.lock
Labels: [Status] Waiting

#1925 Update dependencies
  package.json
  yarn.lock
Labels: [Priority] High, [Type] Tooling

#1933 Bump trim-newlines down to 3.0.1
  package.json
  yarn.lock
Labels: [Priority] High, [Status] Needs Review, [Type] Bug

#1934 Update all compatibility versions for WP 5.8
  class-coblocks.php
  package.json
  readme.txt
Labels: [Status] Needs Review, [Type] Maintenance

#1937 Fix Social block undefined index
  src/blocks/share/index.php
  src/blocks/social-profiles/index.php
Labels: [Type] Bug

#1938 Enhance E2E tests to look for PHP errors in the DOM
  .circleci/config.yml
  .dev/tests/cypress/helpers.js
Labels: [Status] Needs Review, [Type] Tests

#1942 Change npm to yarn in the doc
  docs/contributors/getting-started.md
Labels: [Type] Docs

#1943 Convert Gist Edit component to React hooks
  src/blocks/gist/edit.js
Labels: [Priority] Low, [Type] Code Quality, [Type] Maintenance

#1949 Fix Font Size controls in WordPress 5.8
  src/blocks/author/inspector.js
  src/blocks/click-to-tweet/inspector.js
  src/blocks/gallery-stacked/inspector.js
  src/blocks/highlight/controls.js
  src/blocks/highlight/edit.js
  src/blocks/highlight/inspector.js
  src/blocks/highlight/test/highlight.cypress.js
  src/components/fontsize-picker/index.js
  src/utils/helper.js
Labels: [Priority] Critical, [Type] Bug

#1965 Keep default experimental features object structure within editor settings
  src/extensions/colors/settings-modal-control.js
Labels: [Type] Bug

#1939 Load CoBlocks assets when wp_template_part post type contains a CoBlocks block
  includes/class-coblocks-block-assets.php
Labels: [Priority] Low, [Status] Needs Review, [Type] Needs Tests

#1946 ISBAT render a Gist with a file that has a capitalized letter in the name
  src/blocks/gist/controls.js
  src/blocks/gist/edit.js
  src/blocks/gist/gist.js
  src/blocks/gist/inspector.js
  src/blocks/gist/test/gist.cypress.js
Labels: [Type] Bug
