Repository godaddy-wordpress/coblocks, pull requests merged in 2021-10, with the labels that each got.

#2052 Remove stacked gallery margin when gutter is set to 0
  src/blocks/gallery-stacked/styles/editor.scss
  src/components/responsive-tabs-control/index.js
Labels: [Priority] Low, [Status] Needs Review

#2053 Add services block example
  src/blocks/services/example.js
  src/blocks/services/index.js
Labels: [Priority] Low, [Status] Needs Review

#2056 Fix Hero and Shape Divider resize function
  src/blocks/hero/edit.js
  src/blocks/shape-divider/edit.js
Labels: [Type] Bug, [Priority] Critical

#2051 Fix custom colors on Alert block
  src/blocks/alert/edit.js
Labels: [Type] Bug, [Status] Needs Review
