Repository godaddy-wordpress/coblocks, pull requests merged in 2021-02, with the labels that each got.

#1802 Fix console warning message to block
  CONTRIBUTORS.md
  src/blocks/gist/gist.js
Labels: [Type] Bug, [Type] Code Quality

#1810 Allow Logos & Badges block to behave responsively
  src/blocks/logos/styles/style.scss
Labels: [Type] Bug

#1804 Add replace image button to Collage block gallery items
  .dev/tests/cypress/fixtures/images/150x150-2.png
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/styles/editor.scss
  src/blocks/gallery-collage/styles/style.scss
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
Labels: [Status] Needs Review

#1816 Use Shim when window property undefined
  src/extensions/layout-selector/hooks/useComputedLayouts.js
  src/utils/background-task-api.js
Labels: [Priority] Critical, [Type] Bug

#1817 Use DockerHub auth
  .circleci/config.yml
Labels: [Priority] Critical, [Type] Bug

#1821 Try new focus styles for the Layout Selector
  src/extensions/layout-selector/editor.scss
Labels: [Status] Needs Review, [Type] Enhancement

#1807 Add Link to images within Service Item blocks
  src/blocks/services/edit.js
  src/blocks/services/service/block.json
  src/blocks/services/service/edit.js
  src/blocks/services/service/save.js
  src/blocks/services/service/styles/style.scss
Labels: [Status] In Progress

#1820 Update Gist block styles to resemble ShortCode block
  src/blocks/gist/edit.js
  src/blocks/gist/styles/editor.scss
Labels: [Status] Needs Review

#1818 Remove unintentional limit on block patterns
  includes/class-block-patterns.php
Labels: [Type] Enhancement

#1822 Fix Author block button removal and image placeholder alignment
  src/blocks/author/edit.js
  src/blocks/author/styles/editor.scss
Labels: [Type] Bug

#1825 Fix Posts block layout
  class-coblocks.php
  src/blocks/posts/block.json
  src/blocks/posts/edit.js
  src/blocks/posts/index.php
  src/blocks/posts/styles/style.scss
  src/components/gutter-control/gutter-wrapper.php
  src/utils/utils.php
Labels: [Status] Needs Review, [Type] Bug

#1823 Fix Gallery captions focus
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/components/block-gallery/gallery-image.js
Labels: [Priority] High, [Type] Bug

#1824 Try using PHP 7.4
  .circleci/config.yml
Labels: [Type] Tests

#1831 WPEX-1022 Remove animations from Layouts Selector
  .dev/tests/jest/helpers.js
  src/extensions/layout-selector/layout-selector-results.js
  src/extensions/layout-selector/test/layout-preview.spec.js
Labels: [Status] Ready to Merge

#1833 Fix outstanding E2E test failures
  .dev/bin/install-mailhog.sh
  .dev/tests/cypress/helpers.js
  src/blocks/form/test/form.cypress.js
  src/blocks/highlight/test/highlight.cypress.js
  src/blocks/icon/inspector.js
  src/blocks/icon/test/icon.cypress.js
  src/components/media-filter-control/test/media-filter-control.cypress.js
Labels: [Type] Code Quality, [Type] Tests
