Repository godaddy-wordpress/coblocks, pull requests merged in 2021-12, with the labels that each got.

#2191 Remove the From header in the form block
  includes/class-coblocks-form.php
Labels: [Priority] Low

#2183 Fix CoBlocksFontSizePicker component
  src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
  src/blocks/highlight/edit.js
  src/blocks/highlight/save.js
  src/components/fontsize-picker/index.js
Labels: [Type] Enhancement, [Priority] Low

#2208 Prevent "jumping" Form block layout within editor.
  src/blocks/form/styles/editor.scss
Labels: [Type] Bug, [Status] Needs Review
