Repository godaddy-wordpress/coblocks, pull requests merged in 2021-03, with the labels that each got.

#1835 Fix Gallery Carousel navigation with multiple blocks
  package.json
  src/blocks/gallery-carousel/block.json
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/save.js
  src/blocks/gallery-carousel/test/__snapshots__/save.spec.js.snap
  src/blocks/gallery-carousel/test/deprecated.spec.js
  src/blocks/gallery-carousel/test/save.spec.js
  yarn.lock
Labels: [Status] Needs Review, [Type] Bug

#1838 Close FontSizes bug that exists with WP 5.6.1 but fixed with 5.6.2
  src/blocks/highlight/test/highlight.cypress.js
Labels: [Type] Tests

#1836 Introduce Contextual Errors to Cypress Window operations
  .dev/tests/cypress/helpers.js
  src/components/media-filter-control/test/media-filter-control.cypress.js
  src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
Labels: [Status] Needs Review, [Type] Enhancement, [Type] Tests

#1839 Fix E2E tests for Media Filter component
  .dev/bin/setup-test-specs.sh
  src/components/media-filter-control/test/media-filter-control.cypress.js
Labels: [Type] Tests

#1846 Fix services block image height in TwentyTwentyOne
  .dev/tests/phpunit/includes/test-coblocks-body-classes.php
  includes/class-coblocks-body-classes.php
  src/blocks/services/styles/editor.scss
Labels: [Type] Bug

#1840 Add a from: header to the form emails.
  includes/class-coblocks-form.php
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1847 Set opacity to 1 on .coblocks-animate when in AMP
  includes/class-coblocks-body-classes.php
  src/extensions/animation/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug

#1845 Introduce WordPress 5.7 changes
  .circleci/config.yml
  .dev/tests/cypress/helpers.js
  docs/dev/test-override.md
  package.json
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/post-carousel/test/post-carousel.cypress.js
  src/blocks/services/test/services.cypress.js
  src/blocks/share/test/share.cypress.js
  src/blocks/social-profiles/test/social-profiles.cypress.js
  src/components/typography-controls/index.js
  src/extensions/animation/controls.js
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-store.js
  src/extensions/coblocks-settings/index.js
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/lightbox-controls/test/lightbox-controls.cypress.js
  src/extensions/padding-controls/test/padding-controls.cypress.js
  yarn.lock
Labels: [Priority] Critical, [Status] Needs Review

#1851 Fix for the fact that sometimes too much accordion items were added
  CONTRIBUTORS.md
  src/blocks/accordion/edit.js
  src/blocks/accordion/test/accordion.cypress.js
Labels: [Type] Bug

#1852 Fix Logos & Badges block sizing behavior
  src/blocks/logos/save.js
Labels: [Type] Bug

#1854 Improve Food & Drink block test reliability
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
Labels: [Type] Tests

#1856 When two or more gists on an edit page, fix so that they render properly
  src/blocks/gist/gist.js
  src/blocks/gist/test/gist.cypress.js
Labels: [Type] Bug

#1863 Issue 1580
  src/blocks/hero/controls.js
  src/blocks/hero/test/hero.cypress.js
  src/components/background/controls.js
Labels: [Type] Bug

#1864 Issue 1862
  src/extensions/padding-controls/padding-wrapper.js
  src/extensions/padding-controls/test/padding-wrapper.spec.js
Labels: [Type] Bug

#1867 Fix superfluous style applied within Cover blocks
  src/extensions/image-styles/styles/style.scss
Labels: [Type] Bug

#1857 Bug fix for text color in Hero block
  src/blocks/hero/deprecated.js
  src/blocks/hero/save.js
  src/blocks/hero/test/hero.cypress.js
Labels: [Type] Bug
