Repository godaddy-wordpress/coblocks, pull requests merged in 2021-11, with the labels that each got.

#2130 Remove jQuery from Google Maps script
  src/js/coblocks-google-maps.js
Labels: [Type] Enhancement

#2144 Enable PHPCS cache
  .circleci/config.yml
  phpcs.xml
Labels: [Type] Enhancement, [Type] Tooling

#2154 Attach artifacts in build
  .circleci/config.yml
  .dev/bin/comment-on-pr.sh
Labels: [Type] Enhancement, [Type] Tooling

#2149 Add Request a Quote variation to Form block
  package.json
  src/blocks/form/deprecatedTemplates/icons.js
  src/blocks/form/deprecatedTemplates/layouts.js
  src/blocks/form/fields/field-label.js
  src/blocks/form/icons.js
  src/blocks/form/index.js
  src/blocks/form/styles/style.scss
  src/blocks/form/variations.js
  yarn.lock
Labels: [Status] In Progress

#2163 Filter comments to return godaddy bot comments only
  .dev/bin/comment-on-pr.sh
Labels: [Type] Tooling

#2049 Remove Carousel block example
  src/blocks/gallery-carousel/index.js
Labels: [Type] WP Core Bug

#2162 Performance - Split JS into chunks
  .dev/config/webpack.config.js
  .dev/tests/phpunit/src/extensions/layout-selector/test-index.php
  .dev/tests/phpunit/test-class-coblocks.php
  includes/class-coblocks-block-assets.php
  src/blocks-1.js
  src/blocks-2.js
  src/blocks-3.js
  src/blocks-4.js
  src/blocks-5.js
  src/blocks-6.js
  src/blocks-7.js
  src/blocks-8.js
  src/blocks.js
  src/blocks/click-to-tweet/deprecated.js
  src/extensions.js
  src/extensions/typography/constants.js
  src/extensions/typography/deprecated.js
  src/extensions/typography/index.js
  src/utils/helper.js
Labels: [Type] Performance

#2161 Parallelize performance tests
  .circleci/config.yml
  .dev/performance/cli-results.js
  .dev/performance/index.js
  .dev/performance/results.js
Labels: [Type] Enhancement, [Type] Tooling

#2178 Add a check in the aggregate_perf_test_results build
  .circleci/config.yml
Labels: [Type] Enhancement, [Priority] High, [Type] Tooling
