Repository godaddy-wordpress/coblocks, pull requests merged in 2021-09, with the labels that each got.

#2012 Add a 'replace' button to the service image
  src/blocks/services/service/edit.js
Labels: [Type] Enhancement, [Priority] Low, [Status] Needs Review, [Type] Needs Tests

#2039 Test incoming performance changes
  .circleci/config.yml
  .dev/performance/index.js
Labels: [Status] Needs Review, [Type] Tests

#1967 Update icons to utilize icon package
  .circleci/config.yml
  src/blocks/click-to-tweet/icon.js
  src/blocks/click-to-tweet/index.js
  src/blocks/media-card/index.js
  src/blocks/media-card/media-container.js
  src/components/background/controls.js
  src/components/background/icons.js
  src/components/dimensions-control/icons.js
  src/components/dimensions-control/index.js
  src/components/dimensions-control/styles/editor.scss
  src/components/responsive-base-control/icons.js
  src/components/responsive-base-control/index.js
  src/components/typography-controls/icons.js
  src/components/typography-controls/index.js
  src/utils/block-category.js
  src/utils/brand-assets.js
Labels: [Priority] Low, [Status] Needs Review

#2041 Try using getBlocks selectors directly to check performance gain
  src/blocks/hero/edit.js
  src/blocks/shape-divider/edit.js
Labels: [Status] Needs Review

#2044 Fix the resizable block handles for the Logos and Badges block
  src/blocks/logos/logos.js
  src/blocks/logos/styles/editor.scss
Labels: [Type] Bug, [Status] Needs Review
