Repository godaddy-wordpress/coblocks, pull requests merged in 2021-05, with the labels that each got.

#1893 Show a snackbar notice when a layout is added to a page
  .circleci/config.yml
  src/extensions/layout-selector/index.js
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1894 Fix invalid value passed to layered collage
  src/blocks/gallery-collage/edit.js
Labels: [Priority] High, [Status] Needs Review

#1895 Remove the shadow from collage gallery placeholders
  src/blocks/gallery-collage/edit.js
Labels: [Priority] Low, [Status] Needs Review

#1897 Collage Gallery refactor to hooks and smash bugs
  src/blocks/gallery-collage/controls.js
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/inspector.js
  src/blocks/gallery-collage/styles/style.scss
Labels: [Type] Bug

#1896 Carousel Gallery refactor to hooks and smash bugs
  src/blocks/gallery-carousel/controls.js
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/inspector.js
  src/blocks/gallery-carousel/styles/editor.scss
  src/components/block-gallery/styles/editor.scss
  src/components/slider-panel/index.js
Labels: [Type] Bug

#1871 Add rtl prop to slick-slider component based on if locale is set to rtl
  .dev/tests/phpunit/src/blocks/post-carousel/test-index.php
  src/blocks/post-carousel/edit.js
  src/blocks/post-carousel/index.php
Labels: [Type] Bug

#1903 Try using 'small' default gutter value for Offset block example
  src/blocks/gallery-offset/deprecated.js
  src/blocks/gallery-offset/index.js
  src/components/gutter-control/gutter-control.js
Labels: [Status] Needs Review
