Repository godaddy-wordpress/coblocks, pull requests merged in 2021-04, with the labels that each got.

#1877 Fix image replace flow for core gallery block
  src/components/block-gallery/styles/editor/_gallery-item.scss
Labels: [Type] Bug, [Type] WP Core Bug

#1855 Convert multiple images into a Masonry Gallery block
  .dev/tests/cypress/helpers.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/test/transforms.spec.js
  src/blocks/gallery-carousel/transforms.js
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/save.js
  src/blocks/gallery-collage/test/__snapshots__/save.spec.js.snap
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-collage/test/save.spec.js
  src/blocks/gallery-collage/test/transforms.spec.js
  src/blocks/gallery-collage/transforms.js
  src/blocks/gallery-masonry/edit.js
  src/blocks/gallery-masonry/test/transforms.spec.js
  src/blocks/gallery-offset/edit.js
  src/blocks/gallery-offset/test/transforms.spec.js
  src/blocks/gallery-offset/transforms.js
  src/blocks/gallery-stacked/edit.js
  src/blocks/gallery-stacked/test/transforms.spec.js
  src/blocks/services/test/services.cypress.js
Labels: [Status] Needs Review

#1870 Introduce image replacement flow to CoBlocks Gallery blocks
  .dev/tests/cypress/fixtures/images/R150x150.png
  .dev/tests/cypress/helpers.js
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-collage/test/gallery-collage.cypress.js
  src/blocks/gallery-masonry/edit.js
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/edit.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/edit.js
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/components/block-gallery/gallery-image.js
  src/components/block-gallery/styles/editor.scss
Labels: [Status] Needs Review

#1876 Fix width of images in image filter previews
  src/extensions/animation/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1874 Fix layouts jumping around within the Layout Selector in Safari
  src/extensions/layout-selector/editor.scss
Labels: [Status] Needs Review

#1875 Fix posts block margin in Safari and IE
  src/blocks/posts/styles/style.scss
Labels: [Status] Needs Review

#1702 Shift getPhrasingContentSchema to @wordpress/dom
  src/blocks/highlight/transforms.js
Labels: [Status] Do Not Merge, [Type] Code Quality, [Type] Gutenberg

#1869 Refactor the settings modal to simplify and isolate each control's implementation
  .dev/tests/cypress/helpers.js
  includes/class-coblocks-settings.php
  src/components/typography-controls/index.js
  src/extensions/animation/constants.js
  src/extensions/animation/controls.js
  src/extensions/animation/index.js
  src/extensions/animation/settings-modal-control.js
  src/extensions/animation/test/settings-modal-control.cypress.js
  src/extensions/coblocks-settings/coblocks-settings-modal.js
  src/extensions/coblocks-settings/coblocks-settings-slot.js
  src/extensions/coblocks-settings/coblocks-settings-store.js
  src/extensions/coblocks-settings/coblocks-settings-toggle-control.js
  src/extensions/coblocks-settings/index.js
  src/extensions/coblocks-settings/section.js
  src/extensions/coblocks-settings/styles/style.scss
  src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
  src/extensions/colors/constants.js
  src/extensions/colors/inspector.js
  src/extensions/colors/settings-modal-control.js
  src/extensions/colors/test/settings-modal-control.cypress.js
  src/extensions/layout-selector/constants.js
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/settings-modal-control.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/layout-selector/test/settings-modal-control.cypress.js
  src/extensions/typography/constants.js
  src/extensions/typography/index.js
  src/extensions/typography/settings-modal-control.js
  src/extensions/typography/test/settings-modal-control.cypress.js
Labels: [Status] Needs Review

#1885 Fix missing Group block class
  src/extensions/padding-controls/padding-wrapper.js
  src/extensions/padding-controls/test/padding-wrapper.spec.js
Labels: [Priority] Critical, [Type] Bug

#1886 Fix services block selected state box shadow
  src/blocks/services/styles/editor.scss
Labels: [Priority] Low, [Status] Needs Review

#1884 Fix stacked gallery preview margin
  src/styles/editor.scss
  src/styles/editor/preview.scss
Labels: [Priority] Low, [Status] Needs Review

#1866 Enhance Services block
  src/blocks/author/save.js
  src/blocks/events/event-item/save.js
  src/blocks/food-and-drinks/food-item/edit.js
  src/blocks/food-and-drinks/food-item/save.js
  src/blocks/pricing-table/pricing-table-item/save.js
  src/blocks/services/edit.js
  src/blocks/services/service/edit.js
  src/blocks/services/service/styles/editor.scss
  src/blocks/services/service/styles/style.scss
  src/blocks/services/service/test/service.cypress.js
  src/blocks/services/styles/editor.scss
  src/blocks/services/styles/style.scss
  src/blocks/services/test/services.cypress.js
  src/blocks/services/utilities.js
  src/js/coblocks-fromEntries.js
  yarn.lock
Labels: [Type] Enhancement

#1891 add default align property to gallery collage block
  src/blocks/gallery-collage/block.json
  src/blocks/gallery-collage/test/__snapshots__/save.spec.js.snap
Labels: [Type] Enhancement

#1883 Fix gallery gutter values not set
  src/blocks/gallery-carousel/inspector.js
  src/blocks/gallery-stacked/inspector.js
  src/components/responsive-tabs-control/index.js
Labels: [Type] Bug

#1892 Force typing form inputs in E2E environment
  src/blocks/form/test/form.cypress.js
Labels: [Type] Tests
