Repository godaddy-wordpress/coblocks, pull requests merged in 2021-06, with the labels that each got.

#1908 Fix excess padding on Accordion block
  src/blocks/accordion/accordion-item/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug

#1909 Bring the farthest back image to the front when it's selected in the layered gallery block
  src/blocks/gallery-collage/edit.js
  src/blocks/gallery-collage/styles/style.scss
Labels: [Priority] Low, [Status] Needs Review, [Type] Enhancement

#1905 Try Carousel block variations
  src/blocks/gallery-carousel/edit.js
  src/blocks/gallery-carousel/icons.js
  src/blocks/gallery-carousel/index.js
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-carousel/variations.js
  src/components/block-gallery/gallery-placeholder.js
Labels: [Status] Needs Review, [Type] Enhancement

#1916 Improve release documentation.
  docs/dev/release.md
Labels: [Status] Needs Review, [Type] Docs

#1917 Fix image link controls for Services block
  src/blocks/services/service/edit.js
Labels: [Type] Bug

#1920 Fix background color of Accordion Items taking precedence over user selection
  src/blocks/accordion/accordion-item/styles/style.scss
Labels: [Status] Needs Review, [Type] Bug
