Repository godaddy-wordpress/coblocks, pull requests merged in 2022-01, with the labels that each got.

#2189 Batch use of filters across custom extensions and components
  src/blocks/accordion/edit.js
  src/blocks/shape-divider/deprecated.js
  src/blocks/shape-divider/test/deprecated.spec.js
  src/components/form-label-colors/index.js
  src/components/gutter-control/index.js
  src/components/info-popover/index.js
  src/components/media-filter-control/index.js
  src/components/slider-panel/index.js
  src/components/swiper/index.js
  src/extensions.js
  src/extensions/advanced-controls/index.js
  src/extensions/animation/index.js
  src/extensions/apply-extensions.js
  src/extensions/attributes/index.js
  src/extensions/block-patterns/index.js
  src/extensions/button-controls/index.js
  src/extensions/coblocks-settings/index.js
  src/extensions/colors/inspector.js
  src/extensions/image-crop/index.js
  src/extensions/image-filter/index.js
  src/extensions/lightbox-controls/index.js
  src/extensions/padding-controls/index.js
  src/extensions/replace-image/index.js
  src/extensions/typography/controls.js
  src/extensions/typography/index.js
  src/styles/style.scss
Labels: [Status] Needs Review, [Type] Performance

#2219 Fix Gist file embed
  src/blocks/gist/index.js
  src/blocks/gist/index.php
Labels: [Type] Bug

#2186 Rewrite the Map Block to hooks and modern libraries
  package.json
  src/blocks/map/edit-gmaps-iframe-render.js
  src/blocks/map/edit-gmaps-with-api-key.js
  src/blocks/map/edit.js
  src/blocks/map/index.js
  src/blocks/map/inspector.js
  src/blocks/map/styles.js
  src/blocks/map/test/map.cypress.js
  src/blocks/map/transforms.js
  yarn.lock
Labels: [Type] Enhancement, [Status] Needs Review

#2209 Remove disabled styles inside editor.
  src/blocks/form/styles/editor.scss
Labels: [Type] Bug, [Status] Needs Review

#2239 Fix Lightbox for Gallery block.
  src/extensions/lightbox-controls/index.js
  src/js/coblocks-lightbox.js
Labels: [Type] Bug, [Priority] Critical

#2238 Fix Row, Column and Posts blocks tests for WP 5.9
  src/blocks/posts/test/posts.cypress.js
  src/blocks/row/column/test/column.cypress.js
  src/blocks/row/test/row.cypress.js
Labels: [Status] Needs Review, [Type] Tests

#2224 Introduce Counter Block
  .dev/tests/cypress/helpers.js
  includes/class-coblocks-block-assets.php
  package.json
  src/blocks-13.js
  src/blocks/counter/block.json
  src/blocks/counter/controls.js
  src/blocks/counter/counter.js
  src/blocks/counter/edit.js
  src/blocks/counter/index.js
  src/blocks/counter/index.php
  src/blocks/counter/inspector.js
  src/blocks/counter/save.js
  src/blocks/counter/styles/style.scss
  src/blocks/counter/test/__snapshots__/save.spec.js.snap
  src/blocks/counter/test/counter.cypress.js
  src/blocks/counter/test/save.spec.js
  src/blocks/icon/svgs-generated.js
  src/blocks/icon/svgs/svg/counter.svg
  src/blocks/icon/svgs/svg/testimonial.svg
  src/js/coblocks-counter.js
  src/styles/style.scss
  webpack.config.js
  yarn.lock
Labels: [Status] Needs Review

#2253 Fix some tests in Twenty Twenty-Two
  src/blocks/social-profiles/test/social-profiles.cypress.js
  src/extensions/lightbox-controls/test/lightbox-controls.cypress.js
  src/extensions/media-text-styles/test/media-text-styles.cypress.js
Labels: [Status] Needs Review, [Type] Tests
