Repository godaddy-wordpress/coblocks, pull requests merged in 2022-03, with the labels that each got.

#2297 WPEX-1661 - add preview for event and event-item
  src/blocks/events/event-item/example.js
  src/blocks/events/event-item/index.js
  src/blocks/events/index.js
Labels: [Type] Bug, [Status] Needs Review

#2299 WPEX-1663 allow spacer block as an inner block of feature block
  src/blocks/features/feature/edit.js
Labels: [Type] Enhancement

#2314 Try removing .lock caches from CI config
  .circleci/config.yml
Labels: [Status] Needs Review

#2309 Tweak form block styles
  src/blocks/form/fields/field-label.js
  src/blocks/form/variations.js
Labels: [Type] Enhancement, [Type] Design

#2319 Fix iCal WPCS errors/warnings
  includes/ical-parser/class-coblocks-ical.php
  phpcs.xml
Labels: [Type] Enhancement

#2313 Update some dependencies
  package.json
  yarn.lock
Labels: [Type] Enhancement, [Type] Maintenance

#2322 Update block assets PHP syntax
  includes/class-coblocks-block-assets.php
Labels: [Type] Enhancement

#2310 issue-2304 remove tab index from accordion item content div on front end
  src/blocks/accordion/accordion-item/deprecated.js
  src/blocks/accordion/accordion-item/save.js
  src/blocks/accordion/accordion-item/test/__snapshots__/save.spec.js.snap
Labels: [Type] Bug
