Repository godaddy-wordpress/coblocks, pull requests merged in 2022-05, with the labels that each got.

#2362 Migrate alert block to core/paragraph
  includes/block-migrate/class-coblocks-alert-migration.php
  includes/block-migrate/loader.php
  src/block-styles/core/paragraph/index.js
  src/block-styles/core/paragraph/style.scss
  src/block-variations/core/paragraph/index.js
  src/blocks/alert/block.json
  src/blocks/alert/colors.js
  src/blocks/alert/controls.js
  src/blocks/alert/deprecated.js
  src/blocks/alert/edit.js
  src/blocks/alert/index.js
  src/blocks/alert/inspector.js
  src/blocks/alert/save.js
  src/blocks/alert/test/__snapshots__/save.spec.js.snap
  src/blocks/alert/test/alert.cypress.js
  src/blocks/alert/test/deprecated.spec.js
  src/blocks/alert/test/save.spec.js
  src/blocks/alert/test/transforms.spec.js
  src/blocks/alert/transforms.js
  src/blocks/gist/index.js
  src/extensions.js
  src/styles/index.scss
Labels: [Type] Enhancement, [Type] Needs Tests

#2312 Issue 2305 - add tab index to carousel thumbnails
  src/blocks/gallery-carousel/deprecated.js
  src/blocks/gallery-carousel/save.js
  src/blocks/gallery-carousel/styles/style.scss
  src/blocks/gallery-carousel/test/__snapshots__/save.spec.js.snap
Labels: [Type] Bug, [Type] Enhancement, [Status] Needs Review, [Type] a11y

#2371 Migrate dynamic HR to core/separator
  includes/block-migrate/class-coblocks-dynamic-separator-migration.php
  includes/block-migrate/loader.php
  src/blocks/dynamic-separator/block.json
  src/blocks/dynamic-separator/colors.js
  src/blocks/dynamic-separator/deprecated.js
  src/blocks/dynamic-separator/edit.js
  src/blocks/dynamic-separator/index.js
  src/blocks/dynamic-separator/inspector.js
  src/blocks/dynamic-separator/save.js
  src/blocks/dynamic-separator/styles/editor.scss
  src/blocks/dynamic-separator/test/__snapshots__/save.spec.js.snap
  src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
  src/blocks/dynamic-separator/test/save.spec.js
  src/blocks/dynamic-separator/test/transforms.spec.js
  src/blocks/dynamic-separator/transforms.js
  src/styles/index.scss
Labels: [Type] Enhancement

#2369 WPEX-1925 - adjust focus color on accordion block
  src/blocks/accordion/accordion-item/styles/style.scss
Labels: [Type] Bug, [Type] a11y

#2382 Issue-2115: Reintroduce transformation unit tests for CoBlocks Galleries to Core
  CONTRIBUTORS.md
  src/blocks/gallery-carousel/test/transforms.spec.js
  src/blocks/gallery-collage/test/transforms.spec.js
  src/blocks/gallery-masonry/test/transforms.spec.js
  src/blocks/gallery-offset/test/transforms.spec.js
  src/blocks/gallery-stacked/test/transforms.spec.js
Labels: [Type] Code Quality, [Priority] Low, [Type] Tests
