Repository godaddy-wordpress/coblocks, pull requests merged in 2023-08, with the labels that each got.

#2545 Fix RichText controls in 6.2.2 and 6.3
  package.json
  src/blocks/gallery-carousel/gallery-carousel-item.js
  src/components/block-gallery/gallery-image.js
Labels: [Type] Enhancement

#2555 Fix the radio label not being set properly
  includes/class-coblocks-form.php
Labels: [Type] Enhancement

#2557 Check that data is an array in the form block
  includes/class-coblocks-form.php
Labels: [Type] Bug

#2558 Fix the name field display/email order
  includes/class-coblocks-form.php
Labels: [Type] Bug

#2563 Fix content stripping due to Highlight block raw transform
  src/blocks/highlight/test/transforms.spec.js
  src/blocks/highlight/transforms.js
  src/utils/get-phrasing-content-schema.js
Labels: [Priority] Critical, [Status] Needs Review
