Repository godaddy-wordpress/coblocks, pull requests merged in 2023-02, with the labels that each got.

#2451 GitHub Actions Migration
  .circleci/config.yml
  .dev/tests/cypress/helpers.js
  .dev/tests/cypress/readme.md
  .dev/tests/cypress/support/commands.js
  .distinclude
  .github/workflows/deploy-create-artifact.yml
  .github/workflows/deploy-create-release.yml
  .github/workflows/deploy-wordpress.yml
  .github/workflows/github-codeql-analysis.yml
  .github/workflows/github-labeler.yml
  .github/workflows/test-accessibility.yml
  .github/workflows/test-e2e-cypress.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-javascript.yml
  .github/workflows/test-php-unit.yml
  .github/workflows/test-php.yml
  .github/workflows/translation-localization.yml
  .github/workflows/validation-coding-standards.yml
  .nvmrc
  cypress.config.js
  package.json
  src/components/media-filter-control/test/media-filter-control.cypress.js
  src/extensions/animation/test/settings-modal-control.cypress.js
  src/extensions/colors/test/settings-modal-control.cypress.js
  src/extensions/layout-selector/test/layout-selector.cypress.js
  src/extensions/typography/test/settings-modal-control.cypress.js
Labels: [Type] Enhancement

#2491 convert initial files from enzyme to RTL
  src/extensions/site-content/index.js
  src/extensions/site-content/test/post-menu-actions.spec.js
  src/extensions/site-content/test/site-content.spec.js
  src/extensions/site-design/test/color-palette-preview.spec.js
  src/extensions/site-design/test/design-preview.spec.js
  src/extensions/site-design/test/index.spec.js
Labels: [Status] In Progress

#2470 The Lesser Migration
  .dev/tests/cypress/fixtures/alert.cypress.js.html
  .dev/tests/cypress/fixtures/author.cypress.js.html
  .dev/tests/cypress/helpers.js
  .dev/tests/phpunit/compare-block-attributes.php
  .dev/tests/phpunit/includes/block-migrate/test-coblocks-block-migration.php
  .dev/tests/phpunit/src/blocks/alert/test-index.php
  .dev/tests/phpunit/src/blocks/author/test-index.php
  .github/workflows/test-e2e-cypress.yml
  class-coblocks.php
  includes/block-migrate/class-coblocks-alert-migration.php
  includes/block-migrate/class-coblocks-author-migration.php
  includes/block-migrate/class-coblocks-block-migration-runner.php
  includes/block-migrate/class-coblocks-block-migration.php
  includes/block-migrate/loader.php
  includes/class-coblocks-block-assets.php
  src/block-styles/core/paragraph/index.js
  src/block-styles/core/paragraph/style.scss
  src/block-variations/core/columns/index.js
  src/block-variations/core/paragraph/index.js
  src/blocks/alert/block.json
  src/blocks/alert/colors.js
  src/blocks/alert/controls.js
  src/blocks/alert/deprecated.js
  src/blocks/alert/edit.js
  src/blocks/alert/index.js
  src/blocks/alert/inspector.js
  src/blocks/alert/save.js
  src/blocks/alert/styles/editor.scss
  src/blocks/alert/test/__snapshots__/save.spec.js.snap
  src/blocks/alert/test/alert.cypress.js
  src/blocks/alert/test/deprecated.spec.js
  src/blocks/alert/test/save.spec.js
  src/blocks/alert/test/transforms.spec.js
  src/blocks/alert/transforms.js
  src/blocks/author/block.json
  src/blocks/author/controls.js
  src/blocks/author/deprecated.js
  src/blocks/author/edit.js
  src/blocks/author/index.js
  src/blocks/author/save.js
  src/blocks/author/styles/editor.scss
  src/blocks/author/test/__snapshots__/save.spec.js.snap
  src/blocks/author/test/author.cypress.js
  src/blocks/author/test/deprecated.spec.js
  src/blocks/author/test/save.spec.js
  src/blocks/author/test/transforms.spec.js
  src/blocks/author/transforms.js
  src/extensions.js
  src/styles/index.scss
  src/utils/helper.js
Labels: [Status] Needs Review
