Repository godaddy-wordpress/coblocks, pull requests merged in 2023-03, with the labels that each got.

#2505 Swap get_the_content() for $post->post_content in has_masonry_v1_block()
  includes/class-coblocks-block-assets.php
Labels: [Type] Enhancement

#2510 Update CoBlocks_Site_Design:short_circuit_check to prevent fatal error on WooCommerce system status page on PHP8
  includes/class-coblocks-site-design.php
Labels: [Type] Enhancement, [Type] Woo

#2511 Remove FILTER_SANITIZE_STRING
  includes/admin/class-coblocks-crop-settings.php
  includes/class-coblocks-block-assets.php
  includes/class-coblocks-form.php
  includes/class-coblocks-site-design.php
Labels: [Type] Enhancement

#2501 Minor changes for 6.2 compatibility
  .dev/tests/cypress/helpers.js
  .github/workflows/test-e2e-cypress.yml
  .github/workflows/test-e2e.yml
  .gitignore
  src/blocks/accordion/test/accordion.cypress.js
  src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
  src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
  src/blocks/events/edit.js
  src/blocks/events/test/events.cypress.js
  src/blocks/food-and-drinks/food-item/test/food-item.cypress.js
  src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
  src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
  src/blocks/gallery-masonry/test/gallery-masonry.cypress.js
  src/blocks/gallery-offset/test/gallery-offset.cypress.js
  src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
  src/blocks/icon/test/icon.cypress.js
  src/blocks/logos/test/logos.cypress.js
  src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js
  src/extensions/animation/test/settings-modal-control.cypress.js
  src/extensions/coblocks-labs/test/coblocks-labs.cypress.js
  src/extensions/colors/test/settings-modal-control.cypress.js
  src/extensions/layout-selector/hooks/useCategories.js
  src/extensions/layout-selector/hooks/useComputedLayouts.js
  src/extensions/layout-selector/index.js
  src/extensions/layout-selector/layout-selector-results.js
  src/extensions/layout-selector/store.js
  src/extensions/lightbox-controls/test/lightbox-controls-image.cypress.js
  src/extensions/media-text-styles/test/media-text-styles.cypress.js
  src/extensions/padding-controls/test/padding-controls.cypress.js
  src/extensions/typography/test/settings-modal-control.cypress.js
Labels: [Status] Do Not Merge

#2513 Refactor to use FILTER_SANITIZE_SPECIAL_CHARS
  includes/class-coblocks-block-assets.php
Labels: [Type] Enhancement
